<?php
//--------------------------------------------------------------------
//-  File          : documentation/manpages/template.php
//-  Project       : FVWM Home Page
//-  Programmer    : Uwe Pross
//--------------------------------------------------------------------

// This is an autogenerated file, use manpages2php to create it.

//--------------------------------------------------------------------
// this manpages should not appear in the navigation structure
// so we hide its contents from navgen
//--------------------------------------------------------------------
if (strlen("$navigation_check") > 0) return;

$rel_path = "../../..";

//--------------------------------------------------------------------
// load some global definitions
//--------------------------------------------------------------------
include("$rel_path/definitions.inc");

//--------------------------------------------------------------------
// Site definitions
//--------------------------------------------------------------------
$title          = "FVWM - Man page - FvwmPerl";
$heading        = "FVWM - Man page - FvwmPerl";
$link_name      = "Man page";
$link_picture   = "pictures/icons/doc_manpages";
$parent_site    = "documentation";
$child_sites    = array();
$requested_file = basename(my_get_global("PHP_SELF", "SERVER"));
$this_site      = "manpages";

//--------------------------------------------------------------------
// load the layout file
//--------------------------------------------------------------------
if (strlen($site_has_been_loaded) == 0) {
	$site_has_been_loaded = "true";
	include(sec_filename($layout_file));
	exit();
}
?>

<?php decoration_window_start("Manual page for FvwmPerl in unstable branch (2.5.7)"); ?>

<H1>FVWMPERL</H1>
Section: FVWM Modules (1)<BR>Updated: perl v5.6.0<BR><A HREF="#index">This page contents</A>
 - <a href="./">Return to main index</A><HR>


<A NAME="lbAB">&nbsp;</A>
<H2>NAME</H2>

FvwmPerl - the <FONT>FVWM</FONT> perl manipulator
<A NAME="lbAC">&nbsp;</A>
<H2>SYNOPSIS</H2>

<A NAME="ixAAC"></A>
FvwmPerl is spawned by <I><a href="<?php echo conv_link_target('./fvwm.php');?>">fvwm</a></I>(1), so no command line invocation will work.
<A NAME="lbAD">&nbsp;</A>
<H2>DESCRIPTION</H2>

<A NAME="ixAAD"></A>
This module is intended to extend fvwm commands with the perl scripting
power.  It enables to embed perl expressions in the fvwmrc files and
construct fvwm commands.
<A NAME="lbAE">&nbsp;</A>
<H2>INVOCATION</H2>

<A NAME="ixAAE"></A>
FvwmPerl may be invoked from a fvwmrc file.  If you want to invoke
the unique and persistent instanse of FvwmPerl, it is suggested to
do this from the <I>StartFunction</I>.  Calling it from the top is also
possible, but has several issues not discussed here.
<P>

<blockquote><pre>    AddToFunc StartFunction I Module FvwmPerl</pre></blockquote>
There are several command line switches:
<P>

<B><u>FvwmPerl</u></B>
[ <B>--eval</B> line ]
[ <B>--load</B> file ]
[ <B>--preprocess</B> [ <B>---quote</B> char ] [ <B>---command</B> ]
[ <B>--nosend</B> ] [ <B>---noremove</B> ] [ line | file ] ]
[ <B>--stay</B> ] [ --nolock ]
[ alias ]
<P>

Long switches may be abbreviated to short one-letter switches.
<P>

<B>-e</B>|<B>--eval</B> line - evaluate the given perl code
<P>

<B>-l</B>|<B>--load</B> file - evaluate perl code in the given file
<P>

<B>-p</B>|<B>--preprocess</B> file - preprocess the given fvwmrc file
<P>

<B>-c</B>|<B>--command</B> line - an <FONT>FVWM</FONT> command to be preprocessed instead of file
<P>

<B>-q</B>|<B>--quote</B> char - changes the default '%' quote
<P>

<B>--nosend</B> - do not send the preprocessed file to <I>fvwm</I> for <B>Read</B>ing,
the default is send. Useful for preprocessing non fvwmrc files.
<P>

<B>--noremove</B> - do not remove the preprocessed file after sending
it to <I>fvwm</I> for <B>Read</B>ing, the default is remove. Useful for debugging.
<P>

<B>-s</B>|<B>--stay</B> - continues an execution after <B>---eval</B>, <B>---load</B> or
<B>--preprocess</B> are processed.  By default, the module is not persistent
in this case, i.e. <B>--nostay</B> is assumed.
<P>

<B>--nolock</B> - when one of the 3 action options is given, this option causes
unlocking <I>fvwm</I> immediately. By default the requested action is executed
synchronously; this only makes difference when invoked like:
<P>

<blockquote><pre>  ModuleSynchronous FvwmPerl --preprocess someconfig.ppp</pre></blockquote>
If <B>--nolock</B> is added here, <B>ModuleSynchronous</B> returns immediately.
Note that <B>Module</B> returns immediately regardless of this option.
<A NAME="lbAF">&nbsp;</A>
<H2>ACTIONS</H2>

<A NAME="ixAAF"></A>
There are several actions that FvwmPerl may perform:

<BR>




<DL COMPACT>
<DT><B>eval</B> perl-code<DD>

<A NAME="ixAAG"></A>
Evaluate a line of perl code.


<P>


A special function <B>command(</B>``command''<B>)</B> may be used in perl code to send
commands back to fvwm.


<P>


If perl code contains an error, it is printed to the standard error stream
with the <I>[FvwmPerl][eval]:</I> header prepended.

<BR>




<DT><B>load</B> file-name<DD>

<A NAME="ixAAH"></A>
Load a file of perl code.
If the file is not fully qualified, it is searched in the user
directory <TT>$FVWM_USERDIR</TT> (usually ~/.fvwm) and the system wide
data directory <TT>$FVWM_DATADIR</TT>.


<P>


A special function <B>command(</B>``command''<B>)</B> may be used in perl code to send
commands back to fvwm.


<P>


If perl code contains an error, it is printed to the standard error stream
with the <I>[FvwmPerl][load]:</I> header prepended.

<BR>




<DT><B>preprocess</B> [-q|--quote char] [-c|--command] [<I>line</I> | <I>file</I>]<DD>

<A NAME="ixAAI"></A>
Preprocess fvwmrc <I>file</I> or (if --command is given) <I>line</I>.
This file contains lines that are not touched (usually <FONT>FVWM</FONT> commands)
and specially preformatted perl code that is processed and replaced.
Text enclosed in <B>%{</B> ... <B>}%</B> delimiters, that may start anywhere
on the line and end anywhere on the same or an other line, is perl code.


<P>


The <I>quote</I> parameter changes perl code delimiters.  If a single char
is given, like '@', the delimiters are <B>@{</B> ... <B>}@</B>.
If the given quote is 2 chars, like <B>&lt;&gt;</B>, the quotes are
<B>&lt;{</B> ... <B>}&gt;</B>


<P>


The perl code is substituted for the result of its evaluation.
I.e. %{$a = ``c''; ++$a}% is replaced with ``d''.


<P>


The evaluation is unlike <B>eval</B> and <B>load</B> is done under the
package PreprocessNamespace and without <I>use strict</I>, so you are
free to use any variable names without fear of conflicts. Just don't
use uninitialized variables to mean undef or empty list (they may be in fact
initialized by the previous preprocess action), and do a clean-up if needed.
The variables and function in the <I>main</I> package are still available,
like ::<I>command()</I> or ::<I>skip()</I>, but it is just not a good idea to access them
while preprocessing.


<P>


There is a special function <B>include</B>(<I>file</I>) that loads a file,
preprocesses it and returns the preprocessed result. Avoid recursion.


<P>


If any embedded perl code contains an error, it is printed to the standard
error stream and prepended with the <I>[FvwmPerl][preprocess]:</I> header.
The result of substitution is empty in this case.


<P>


The following variables may be used in the perl code:


<P>


$USER,
<TT>$DISPLAY</TT>,
<TT>$WIDTH</TT>,
<TT>$HEIGHT</TT>,
<TT>$FVWM_VERSION</TT>,
<TT>$FVWM_MODULEDIR</TT>,
<TT>$FVWM_DATADIR</TT>,
<TT>$FVWM_USERDIR</TT>


<P>


The following line based directives are recognized when preprocessing.
They are processed after the perl code (if any) is substituted.
<DL COMPACT><DT><DD>

<BR>




<DL COMPACT>
<DT>%<B>Repeat</B> <I>count</I><DD>

<A NAME="ixAAJ"></A>
Causes the following lines to be repeated <I>count</I> times.

<BR>




<DT>%<B>ModuleConfig</B> <I>module-name</I> [ destroy ]<DD>

<A NAME="ixAAK"></A>
Causes the following lines to be interpreted as the given module configuration.
If ``destroy'' is specified the previous module configuration is destroyed first.

<BR>




<DT>%<B>Prefix</B> <I>prefix</I><DD>

<A NAME="ixAAL"></A>
Prefixes the following lines with the quoted <I>prefix</I>.

<BR>




<DT>%<B>End</B> any-optional-comment<DD>

<A NAME="ixAAM"></A>
Ends any of the directives described above, may be nested.
</DL>
</DL>

<DL COMPACT><DT><DD>


<P>


Examples:


<P>


<blockquote><pre>  %Prefix &quot;AddToFunc SwitchToWindow I&quot;
    Iconify off
    WindowShade off
    Raise
    WrapToWindow 50 50
  %End

  %ModuleConfig FvwmPager destroy
    Colorset 0
    Font lucidasans-10
    DeskTopScale 28
    MiniIcons
  %End ModuleConfig FvwmPager

  %Prefix &quot;All (MyWindowToAnimate) ResizeMove &quot;
  100 100 %{($WIDTH - 100) / 2}% %{($HEIGHT - 100) / 2}%
  %Repeat %{$count}%
  br w+2c w+2c w-1c w-1c
  %End
  %Repeat %{$count}%
  br w-2c w-2c w+1c w+1c
  %End
  %End Prefix</pre></blockquote>
Additional preprocess parameters --nosend and --noremove may be given too.
See their description at the top.
</DL>

</DL>
<P>

These 3 actions may be requested in one of 3 ways: 1) in the command line when
FvwmPerl is invoked (in this case FvwmPerl is short-lived unless <B>--stay</B>
is also given), 2) by sending the corresponding message in fvwmrc using
SendToModule, 3) by calling the corresponding perl function in perl code.
<A NAME="lbAG">&nbsp;</A>
<H2>FUNCTIONS</H2>

<A NAME="ixAAN"></A>
There are several functions that perl code may call:

<BR>




<DL COMPACT>
<DT><B>command(</B><I>$fvwmCommand</I><B>)</B><DD>

<A NAME="ixAAO"></A>
In case of <B>eval</B> or <B>load</B> - send back to fvwm a string <I>$fvwmCommand</I>.
In case of <B>preprocess</B> - append a string <I>$fvwmCommand</I> to the output of
the embedded perl code.

<BR>




<DT><B>doEval(</B><I>$perlCode</I><B>)</B><DD>

<A NAME="ixAAP"></A>
This function is equivalent to the <B>eval</B> functionality
on the string <I>$perlCode</I>, described above.

<BR>




<DT><B>load(</B>$fileName<B>)</B><DD>

<A NAME="ixAAQ"></A>
This function is equivalent to the <B>load</B> functionality
on the file <TT>$fileName</TT>, described above.

<BR>




<DT><B>preprocess(</B><I>@params, [-c </I>$command<I>] [$fileName]</I><B>)</B><DD>



<BR>




<DT><B>preprocess(</B><I>@params, [``-c </I>$command<I>''] [$fileName]</I><B>)</B><DD>


<A NAME="ixAAR"></A>
This function is equivalent to the <B>preprocess</B> functionality
with the given parameters and the file <TT>$fileName</TT> described above.
</DL>
<A NAME="lbAH">&nbsp;</A>
<H2>VARIABLES</H2>

<A NAME="ixAAS"></A>
There are several global variables in the <I>main</I> namespace that may be used
in the perl code:
<P>

<blockquote><pre>    $a, $b, ... $h
    @a, @b, ... @h
    %a, %b, ... %h</pre></blockquote>
They all are initialized to the empty value and may be used to store a state
between different calls to FvwmPerl actions (<B>eval</B> and <B>load</B>).
<P>

If you need more readable variable names, either write ``no strict 'vars';''
at the start of every perl code or use a hash for this, like:
<P>

<blockquote><pre>    $h{id} = $h{firstName} . &quot; &quot; . $h{secondName}</pre></blockquote>
or use a package name, like:
<P>

<blockquote><pre>    @MyMenu::terminals = qw( xterm rxvt );
    $MyMenu::itemNum = @MyMenu::terminals;</pre></blockquote>
There may be a configuration option to turn strictness on and off.
<A NAME="lbAI">&nbsp;</A>
<H2>MESSAGES</H2>

<A NAME="ixAAT"></A>
FvwmPerl may receive messages using the fvwm command SendToModule.
The names, meanings and parameters of the messages are the same as the
corresponding actions, described above.
<P>

Additionally, a message <B>stop</B> causes a module to quit.
A message <B>dump</B> dumps the contents of the changed variables.
<A NAME="lbAJ">&nbsp;</A>
<H2>EXAMPLES</H2>

<A NAME="ixAAU"></A>
A simple test:
<P>

<blockquote><pre>    SendToModule FvwmPerl eval $h{dir} = $ENV{HOME}
    SendToModule FvwmPerl eval load($h{dir} . &quot;/test.fpl&quot;)
    SendToModule FvwmPerl load $[HOME]/test.fpl
    SendToModule FvwmPerl preprocess fvwmrc.ppp
    SendToModule FvwmPerl eval dump(\%h, @a);
    SendToModule FvwmPerl stop</pre></blockquote>
The following example handles root backgrounds in fvwmrc.
All these commands may be added to StartFunction.
<P>

<blockquote><pre>    Module FvwmPerl

    # find all background pixmaps for a later use
    SendToModule FvwmPerl eval $a = $ENV{HOME} . &quot;/bg&quot;; \
      opendir DIR, $a; @b = grep { /xpm$/ } readdir(DIR); closedir DIR

    # build a menu of background pixmaps
    AddToMenu MyBackgrounds &quot;My Backgrounds&quot; Title
    SendToModule FvwmPerl eval foreach $b (@b) \
      { command(&quot;AddToMenu MyBackgrounds '$b' Exec fvwm-root $a/$b&quot;) }

    # choose a random background to load on start-up
    SendToModule FvwmPerl eval command(&quot;AddToFunc \
      InitFunction + I Exec exec fvwm-root $a/&quot; . $b[int(random(@b))])</pre></blockquote>
<A NAME="lbAK">&nbsp;</A>
<H2>ESCAPING</H2>

<A NAME="ixAAV"></A>
<B>SendToModule</B> just like any other fvwm commands expands several dollar
prefixed variables.  This may clash with the dollars perl uses.
You may avoid this by prefixing SendToModule with a leading dash.
The following 2 lines in each pair are equivalent:
<P>

<blockquote><pre>    SendToModule FvwmPerl eval $$d = &quot;$[DISPLAY]&quot;
    -SendToModule FvwmPerl eval $d = &quot;$ENV{DISPLAY}&quot;

    SendToModule FvwmPerl eval \
        command(&quot;Echo desk=$d, display=$$d&quot;)
    SendToModule FvwmPerl preprocess -c \
        Echo desk=%(&quot;$d&quot;)%, display=%{$$d}%</pre></blockquote>
Another solution to avoid escaping of special symbols like dollars
and backslashes is to create a perl file in ~/.fvwm and then load it:
<P>

<blockquote><pre>    SendToModule FvwmPerl load build-menus.fpl</pre></blockquote>
If you need to preprocess one command starting with a dash, you should
precede it using ``--''.
<P>

<blockquote><pre>    # this prints the current desk, i.e. &quot;0&quot;
    SendToModule FvwmPerl preprocess -c Echo &quot;$%{$a = &quot;c&quot;; ++$a}%&quot;
    # this prints &quot;$d&quot;
    SendToModule FvwmPerl preprocess -c -- -Echo &quot;$%{&quot;d&quot;}%&quot;
    # this prints &quot;$d&quot; (SendToModule expands $$ to $)
    SendToModule FvwmPerl preprocess -c -- -Echo &quot;$$%{&quot;d&quot;}%&quot;
    # this prints &quot;$$d&quot;
    -SendToModule FvwmPerl preprocess -c -- -Echo &quot;$$%{&quot;d&quot;}%&quot;</pre></blockquote>
Again, it is suggested to put your <I>command</I>(s) into file and preprocess
the file instead.
<A NAME="lbAL">&nbsp;</A>
<H2>CAVEATS</H2>

<A NAME="ixAAW"></A>
FvwmPerl being written in perl and dealing with perl, follows the famous
perl motto: ``There's more than one way to do it'', so the choice is yours.
<P>

Here are more pairs of equivalent lines:
<P>

<blockquote><pre>    Module FvwmPerl --load &quot;my.fpl&quot; --stay
    Module FvwmPerl -e 'load(&quot;my.fpl&quot;)' -s

    SendToModule FvwmPerl preprocess --quote '@' my.ppp
    SendToModule FvwmPerl eval preprocess({quote =&gt; '@'}, &quot;my.ppp&quot;);</pre></blockquote>
Warning, you may affect the way FvwmPerl works by evaluating appropriate
perl code, this is considered a feature not a bug.  But please don't do this,
write your own <FONT>FVWM</FONT> module in perl instead.
<A NAME="lbAM">&nbsp;</A>
<H2>SEE ALSO</H2>

<A NAME="ixAAX"></A>
The <I><a href="<?php echo conv_link_target('./fvwm.php');?>">fvwm</a></I>(1) man page describes all available commands.
<P>

Basically, in your perl code you may use any function or class method from
the perl library installed with <FONT>FVWM</FONT>, see the man pages of perl packages
<B><a href="<?php echo conv_link_target('./../perllib/General::FileSystem.php');?>">General::FileSystem</a></B>, <B><a href="<?php echo conv_link_target('./../perllib/General::Parse.php');?>">General::Parse</a></B> and <B></B><B><a href="<?php echo conv_link_target('./../perllib/FVWM::Module.php');?>">FVWM::Module</a></B>.
<A NAME="lbAN">&nbsp;</A>
<H2>AUTHOR</H2>

<A NAME="ixAAY"></A>
Mikhael Goikhman &lt;<A HREF="mailto:migo@homemail.com">migo@homemail.com</A>&gt;.
<P>

<HR>
<A NAME="index">&nbsp;</A><H2>Index</H2>
<DL>
<DT><A HREF="#lbAB">NAME</A><DD>
<DT><A HREF="#lbAC">SYNOPSIS</A><DD>
<DT><A HREF="#lbAD">DESCRIPTION</A><DD>
<DT><A HREF="#lbAE">INVOCATION</A><DD>
<DT><A HREF="#lbAF">ACTIONS</A><DD>
<DT><A HREF="#lbAG">FUNCTIONS</A><DD>
<DT><A HREF="#lbAH">VARIABLES</A><DD>
<DT><A HREF="#lbAI">MESSAGES</A><DD>
<DT><A HREF="#lbAJ">EXAMPLES</A><DD>
<DT><A HREF="#lbAK">ESCAPING</A><DD>
<DT><A HREF="#lbAL">CAVEATS</A><DD>
<DT><A HREF="#lbAM">SEE ALSO</A><DD>
<DT><A HREF="#lbAN">AUTHOR</A><DD>
</DL>
<HR>
This document was created by
man2html,
using the manual pages.<BR>
Time: 01:39:56 GMT, April 19, 2003


<?php decoration_window_end(); ?>

<!-- Automatically generated by manpages2php on 19-Apr-2003 -->
