<?php
//--------------------------------------------------------------------
//-  File          : documentation/manpages/template.php
//-  Project       : FVWM Home Page
//-  Programmer    : Uwe Pross
//--------------------------------------------------------------------

// This is an autogenerated file, use manpages2php to create it.

//--------------------------------------------------------------------
// this manpages should not appear in the navigation structure
// so we hide its contents from navgen
//--------------------------------------------------------------------
if (strlen("$navigation_check") > 0) return;

$rel_path = "../../..";

//--------------------------------------------------------------------
// load some global definitions
//--------------------------------------------------------------------
include("$rel_path/definitions.inc");

//--------------------------------------------------------------------
// Site definitions
//--------------------------------------------------------------------
$title          = "FVWM - Man page - FvwmGtkDebug";
$heading        = "FVWM - Man page - FvwmGtkDebug";
$link_name      = "Man page";
$link_picture   = "pictures/icons/doc_manpages";
$parent_site    = "documentation";
$child_sites    = array();
$requested_file = basename(my_get_global("PHP_SELF", "SERVER"));
$this_site      = "manpages";

//--------------------------------------------------------------------
// load the layout file
//--------------------------------------------------------------------
if (strlen($site_has_been_loaded) == 0) {
	$site_has_been_loaded = "true";
	if (strlen($layout) > 0) {
		$file = "$rel_path/layout_$layout.inc";
		if (file_exists($file)) $layout_file = $file;
	}
	include(sec_filename($layout_file));
	exit();
}
?>

<?php decoration_window_start("Manual page for FvwmGtkDebug in unstable branch (2.5.7)"); ?>

<H1>FVWMGTKDEBUG</H1>
Section: FVWM Module (1)<BR>Updated: perl v5.6.0<BR><A HREF="#index">This page contents</A>
 - <a href="./">Return to main index</A><HR>


<A NAME="lbAB">&nbsp;</A>
<H2>NAME</H2>

FvwmGtkDebug - the graphical <FONT>FVWM</FONT> module debugger
<A NAME="lbAC">&nbsp;</A>
<H2>SYNOPSIS</H2>

<A NAME="ixAAC"></A>
FvwmGtkDebug should be spawned by <I><a href="<?php echo conv_link_target('./fvwm.php');?>">fvwm</a></I>(1).
<P>

To run this module, place this command somewhere in the configuration:
<P>

<blockquote><pre>  Module FvwmGtkDebug</pre></blockquote>
To stop this module, just close the <FONT>GUI</FONT> window, the usual KillModule works too.
<P>

You may also run this application in the dummy mode from the command line,
but this only shows the <FONT>GUI</FONT> with dummy event data and not the real data.
<A NAME="lbAD">&nbsp;</A>
<H2>DESCRIPTION</H2>

<A NAME="ixAAD"></A>
This module monitors all fvwm event information and shows it nicely in the
interactive gtk+ application. Good for debugging purposes.
<A NAME="lbAE">&nbsp;</A>
<H2>INVOCATION</H2>

<A NAME="ixAAE"></A>
There are several command line switches:
<P>

<B><u>FvwmGtkDebug</u></B>
[ <B>--mask</B> <I>mask</I> ]
[ <B>--xmask</B> <I>mask</I> ]
<P>

Long switches may be abbreviated to shorter switches.
<P>

<B>-m</B>|<B>--mask</B> <I>mask</I> - set the initial module mask,
this mask may be changed interactivelly at any time
<P>

<B>-x</B>|<B>--xmask</B> <I>mask</I> - set the initial module extended mask,
this mask may be changed interactivelly at any time
<A NAME="lbAF">&nbsp;</A>
<H2>SEE ALSO</H2>

<A NAME="ixAAF"></A>
See the <a href="<?php echo conv_link_target('./FvwmDebug.php');?>">FvwmDebug</a> manpage.
<A NAME="lbAG">&nbsp;</A>
<H2>AUTHOR</H2>

<A NAME="ixAAG"></A>
Mikhael Goikhman &lt;<A HREF="mailto:migo@homemail.com">migo@homemail.com</A>&gt;.
<P>

<HR>
<A NAME="index">&nbsp;</A><H2>Index</H2>
<DL>
<DT><A HREF="#lbAB">NAME</A><DD>
<DT><A HREF="#lbAC">SYNOPSIS</A><DD>
<DT><A HREF="#lbAD">DESCRIPTION</A><DD>
<DT><A HREF="#lbAE">INVOCATION</A><DD>
<DT><A HREF="#lbAF">SEE ALSO</A><DD>
<DT><A HREF="#lbAG">AUTHOR</A><DD>
</DL>
<HR>
This document was created by
man2html,
using the manual pages.<BR>
Time: 01:39:55 GMT, April 19, 2003


<?php decoration_window_end(); ?>

<!-- Automatically generated by manpages2php on 19-Apr-2003 -->
