	  Submitted by Dominik Vogt,
	  shows soft gradients in menus and titlebars, a shaded window on the
	  left side of the top edge, FvwmButtons on the bottom edge, some menus
	  containing directory listings (updated every time they are opened)
	  and a bit of my .fvwm2rc in the top right shell. The colour palette
	  is one of about twenty I hijacked from CDE. Sub menus are nicely
	  centered around their parent item (use
	  'Popup menu-name item +100 c' for this effect).
