	  Submitted by Tenebrae.
	  Here's my latest screenshot running FVWM 2.2.4 under RedHat Linux 6.2.  I
	  have a light marble GTK+ theme that I've extended manually onto my FVWM
	  buttons, and a custom icon or two.  I made the blue Vampire Princess Miyu
	  background for the Eterm, and threw Vampire Princess Miyu skins that I
	  found onto Licq and xmms.  I also customized the title bars a bit with a
	  textured background that fits in with the overall blueness of the Miyu
	  stuff.  Heres the <a href="fvwm2rc">config file</a>.
