<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html> 
  <head>
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
    <meta name="keywords" content="fvwm, window manager, screenshots, themes">
    <meta name="description" content="The Official FVWM Home Page">
    
    <link rel="shortcut icon" href="<?php echo $rel_path; ?>/fvwm.ico">

    <title>No software patents</title>

    <style type="text/css">
    <!--  
      body {
      margin-left:10%;
      margin-right:10%;
      }
     -->
    </style>

  </head>

  <body 
    bgcolor="#ffffff"
    text="#000000"
    link="#0000ff"
    vlink="#ff0000"
    alink="#00ff00">

    <div align=center>
      <h1>Page closed</h1>
      <h3>Page ferm&eacute;e</h3>
      <h3>Seite gesperrt</h3>
    </div>

    <p>
      <font size=+1>
	<b>
	  This page is temporarily closed in protest against software
	  patents.  Websites may soon be closed down regularly due to software
	  patents.  Software patents can get you prosecuted for publishing texts
	  you wrote yourself!
	</b>
      </font>
    </p>

    <p>
      More information about software patents are available at <a href="http://swpat.ffii.org/">swpat.ffii.org</a>.
      To enter this site, click <a href="<?php echo $requested_file;?>?no_software_patents=for_ever">here</a>
     </p>

    <hr>

    <p>
      Diese Seite wurde zum Protest gegen Logikpatente vor&uuml;bergehend
      gesperrt.  Bald k&ouml;nnten Webseiten regelm&auml;&szlig;ig wegen
      Logikpatenten gesperrt werden.  Logikpatente k&ouml;nnen dazu
      f&uuml;hren, dass Sie wegen Ver&ouml;ffentlichung selbst entwickelter
      Texte gerichtlich belangt werden.
    </p>

    <p>
      Mehr &uuml;ber Logikpatente erfahren Sie bei <a href="http://swpat.ffii.org/">swpat.ffii.org</a>.
      Um zu ihren urspr&uuml;nglichen Ziel zu gelangen, klicken Sie bitte <a href="<?php echo $requested_file;?>?no_software_patents=for_ever">hier</a>.
    </p>

    <hr>
    <p>
      Cette page a &eacute;t&eacute; ferm&eacute;e temporairement
      pour protester contre les brevets logiciels.  Bient&ocirc;t les
      pages web pourront &ecirc;tre ferm&eacute;es
      r&eacute;guli&egrave;rement &agrave;  cause des brevets logiciels.
      Avec les brevets logiciels vous pourrez &ecirc;tre condamn&eacute;
      &agrave; cause de textes que vous avez &eacute;crit vous-m&ecirc;me.
    </p>

    <p> 
      Plus d&apos;informations sur les brevets logiciels sont disponibles &agrave; <a href="http://swpat.ffii.org/">swpat.ffii.org</a>.
      Pour 
      arriver &agrave; v&ocirc;tre d&eacute;stination, veuillez cliquer <a href="<?php echo $requested_file;?>?no_software_patents=for_ever">ici</a>.
    </p>
