	  Submitted by An Thi-Nguyen Le.
	  Simple  window  and    menu   decors  using diagonal     and
	  backwards-diagonal gradients.    Buttons are actual defaults
	  from fvwm.  :) The modules used are FvwmButtons (I'd use the
	  $fg and $bg variables for the swallowed shell but that makes
	  it harder to read in this case), FvwmPager, FvwmIconMan (the
	  very bestest icon manager around).  Dockapps are xpostit and
	  wmnetselect.  On the right is GKrellM, nice themable stacked
	  system monitors.
