#!/usr/bin/perl

use strict;

# List of full paths to manpages (currently must gziped .gz)
#my $manfiles = `ls /usr/share/man/man1/*Fvwm*  /usr/share/man/man1/*fvwm*`;
my $manfiles = `ls /home/jaimos/tmp/fvwm-2.6.6/tmp/share/man/man1/*`;

# Index Page Header.
my $index_page = q(---
layout : default
title : Man Pages
---
# FVWM Man Page Index

* * * 
);

my $manpage, my $mantitle, my $manfile, my $body, my $header;
while( $manfiles =~ /(.+)$/mg) {
	$manpage = $1;
	($mantitle = $manpage) =~ s!.*1/(.*).1$!$1!;
	$index_page = "$index_page\n + [__${mantitle}__](${mantitle}.html)";

	# Man Page Header
	$header = "---\nlayout : default\ntitle : Man Page - $mantitle\nheader-title : $mantitle\n---\n";

	# Man Page Body
	local $_ = `cat $manpage | man2html -p`;

	# Trim html header and footer
	s!^.*?<body>(.*)</body>.*$!$1!si;
	s!<HR>\nThis document was created by.*$!!si;

	# Cleanup &nbsp;
	s!&nbsp;!!gi;

	# Change index links
	s!Index!Table of Contents!;
	s!Main Contents!Man Page Index!;
	s!/cgi-bin/man/man2html!index.html!;
	s!/cgi-bin/man/man2html/1\+!!g;

        $body = "<div class=\"manpage-wrapper\">\n$_\n</div>";

	$manfile = "$mantitle.html";
	open FILE, '>'.$manfile;
	
        print FILE $header;
	print FILE $body;

	close FILE;

    print "Created html manpage for: $mantitle\n";
}

# Index Page
print "Creating Index Page.\n";
open FILE, ">index_page.md";
print FILE $index_page;
close FILE

