<?php
//--------------------------------------------------------------------
//-  File          : documentation/manpages/template.php
//-  Project       : FVWM Home Page
//-  Programmer    : Uwe Pross
//--------------------------------------------------------------------

// This is an autogenerated file, use manpages2php to create it.

//--------------------------------------------------------------------
// this manpages should not appear in the navigation structure
// so we hide its contents from navgen
//--------------------------------------------------------------------
if(isset($navigation_check)) return;

$rel_path = "../../..";

//--------------------------------------------------------------------
// load some global definitions
//--------------------------------------------------------------------
include_once("$rel_path/definitions.inc");

//--------------------------------------------------------------------
// Site definitions
//--------------------------------------------------------------------
$title          = "FVWM - Man page - fvwmbug";
$heading        = "FVWM - Man page - fvwmbug";
$link_name      = "Man page";
$link_picture   = "pictures/icons/doc_manpages";
$parent_site    = "documentation";
$child_sites    = array();
$requested_file = basename(my_get_global("PHP_SELF", "SERVER"));
$this_site      = "manpages";

//--------------------------------------------------------------------
// load the layout file
//--------------------------------------------------------------------
if(!isset($site_has_been_loaded)) {
	$site_has_been_loaded = "true";
	include_once(sec_filename($layout_file));
	exit();
}
?>

<?php decoration_window_start("Manual page for fvwmbug in stable branch (2.4.16)"); ?>

<H1>FVWMBUG</H1>
Section: User Commands  (1)<BR>Updated: 3 July 2001<BR><A HREF="#index">This page contents</A>
 - <a href="<?php echo conv_link_target('./');?>">Return to main index</A><HR>

<A NAME="lbAB">&nbsp;</A>
<H2>NAME</H2>

fvwmbug - report a bug in FVWM
<A NAME="lbAC">&nbsp;</A>
<H2>SYNOPSIS</H2>

<B><u>fvwmbug</u></B> [<I>address</I>]
<A NAME="lbAD">&nbsp;</A>
<H2>DESCRIPTION</H2>

<B><u>fvwmbug</u></B>

is a shell script to help the user compose and mail bug reports
concerning FVWM in a standard format.
<B><u>fvwmbug</u></B>

invokes the editor specified by the environment variable
<FONT><B>EDITOR</B>

</FONT>
on a temporary copy of the bug report format outline. The user must
fill in the appropriate fields and exit the editor.
<B><u>fvwmbug</u></B>

then mails the completed report to the local FVWM maintainer, the FVWM workers list
<I><A HREF="mailto:fvwm-workers@fvwm.org">fvwm-workers@fvwm.org</A></I>, or
<I>address</I>.  If the report cannot be mailed, it is saved in the
file <I>dead.fvwmbug</I> in the invoking user's home directory.
<P>

The bug report format outline consists of several sections.  The first
section provides information about the machine, operating system, the
FVWM version, and the compilation environment.  The second section
should be filled in with a description of the bug.  The third section
should be a description of how to reproduce the bug.  The optional
fourth section is for a proposed fix.  Fixes are encouraged.
<A NAME="lbAE">&nbsp;</A>
<H2>ENVIRONMENT</H2>

<B><u>fvwmbug</u></B>

will utilize the following environment variables if they exist:
<DL COMPACT>
<DT><B>EDITOR</B>

<DD>
Specifies the preferred editor. If
<FONT><B>EDITOR</B>

</FONT>
is not set,
<B><u>fvwmbug</u></B>

defaults to
<B>emacs</B>.

<DT><B>HOME</B>

<DD>
Directory in which the failed bug report is saved if the mail fails.
<P>
</DL>

<HR>
<A NAME="index">&nbsp;</A><H2>Index</H2>
<DL>
<DT><A HREF="#lbAB">NAME</A><DD>
<DT><A HREF="#lbAC">SYNOPSIS</A><DD>
<DT><A HREF="#lbAD">DESCRIPTION</A><DD>
<DT><A HREF="#lbAE">ENVIRONMENT</A><DD>
</DL>
<HR>
This document was created by
man2html,
using the manual pages.<BR>
Time: 17:47:38 GMT, May 30, 2003


<?php decoration_window_end(); ?>

<!-- Automatically generated by manpages2php on 30-May-2003 -->
