#!/bin/sh

# Usage: regenerate_pages [optional-relative-fvwm-dir]

this_dir="`dirname $0`"
cd "$this_dir" || exit 1

fvwm_dir="$1"
if [ "$fvwm_dir" = "" ]; then
	fvwm_dir=../fvwm
fi
if [ ! -d "$fvwm_dir" ]; then
	echo Can not find directory "$fvwm_dir"
	exit 2
fi

echo Regenerating 3 index.php

(cd authors/ && gawk -f authors2php <../"$fvwm_dir"/AUTHORS >index.php)
(cd news/ && gawk -f news2php <../"$fvwm_dir"/NEWS >index.php)
(cd documentation/faq/ && gawk -f faq2php <../../"$fvwm_dir"/docs/FAQ >index.php)

echo Done
