<?php
//--------------------------------------------------------------------
//-  File          : documentation/manpages/template.php
//-  Project       : FVWM Home Page
//-  Programmer    : Uwe Pross
//--------------------------------------------------------------------

// This is an autogenerated file, use perllib2php to create it.

//--------------------------------------------------------------------
// this manpages should not appear in the navigation structure
// so we hide its contents from navgen
//--------------------------------------------------------------------
if (strlen("$navigation_check") > 0) return;

$rel_path = "./../..";

//--------------------------------------------------------------------
// load some global definitions
//--------------------------------------------------------------------
include("$rel_path/definitions.inc");

//--------------------------------------------------------------------
// Site definitions
//--------------------------------------------------------------------
$title          = "FVWM - Perl library - FVWM::Constants";
$heading        = "FVWM - Perl library - FVWM::Constants";
$link_name      = "Perl library";
$link_picture   = "pictures/icons/doc_manpages";
$parent_site    = "documentation";
$child_sites    = array();
$requested_file = basename(my_get_global("PHP_SELF", "SERVER"));
$this_site      = "manpages";

//--------------------------------------------------------------------
// load the layout file
//--------------------------------------------------------------------
if (strlen($site_has_been_loaded) == 0) {
	$site_has_been_loaded = "true";
	if (strlen($layout) > 0) {
		$file = "$rel_path/layout_$layout.inc";
		if (file_exists($file)) $layout_file = $file;
	}
	include(sec_filename($layout_file));
	exit();
}
?>

<?php decoration_window_start("Manual page for FVWM::Constants in unstable branch (2.5.8)"); ?>

<H1>FVWM::Constants</H1>
Section: FVWM Perl library (3)<BR>Updated: 2003-06-10<BR>Source: <a href="ftp://ftp.fvwm.org/pub/fvwm/devel/sources/perllib/FVWM/Constants.pm">FVWM/Constants.pm</a><br>
<A HREF="#index">This page contents</A>
 - <a href="./">Return to main index</A><HR>

<A NAME="lbAB">&nbsp;</A>
<H2>NAME</H2>

FVWM::Constants - exports FVWM specific constants
<A NAME="lbAC">&nbsp;</A>
<H2>DESCRIPTION</H2>

<A NAME="ixAAC"></A>
This class is used to load <FONT>FVWM</FONT> constants into your perl script or class.
Note, if you use <I><a href="<?php echo conv_link_target('./FVWM::Module.php');?>">FVWM::Module</a></I> the constants are automatically exported.
So you usually do not need to include this class.
<A NAME="lbAD">&nbsp;</A>
<H2>USAGE</H2>

<A NAME="ixAAD"></A>
<blockquote><pre>  use FVWM::Constants;</pre></blockquote>
<A NAME="lbAE">&nbsp;</A>
<H2>SEE ALSO</H2>

<A NAME="ixAAE"></A>
For more information, see <a href="<?php echo conv_link_target('./FVWM::Module.php');?>">FVWM::Module</a>.
<A NAME="lbAF">&nbsp;</A>
<H2>EXPORTED CONSTANTS</H2>

<A NAME="ixAAF"></A>
<blockquote><pre>  M_NEW_PAGE
  M_NEW_DESK
  M_OLD_ADD_WINDOW
  M_RAISE_WINDOW
  M_LOWER_WINDOW
  M_OLD_CONFIGURE_WINDOW
  M_FOCUS_CHANGE
  M_DESTROY_WINDOW
  M_ICONIFY
  M_DEICONIFY
  M_WINDOW_NAME
  M_ICON_NAME
  M_RES_CLASS
  M_RES_NAME
  M_END_WINDOWLIST
  M_ICON_LOCATION
  M_MAP
  M_ERROR
  M_CONFIG_INFO
  M_END_CONFIG_INFO
  M_ICON_FILE
  M_DEFAULTICON
  M_STRING
  M_MINI_ICON
  M_WINDOWSHADE
  M_DEWINDOWSHADE
  M_VISIBLE_NAME
  M_SENDCONFIG
  M_RESTACK
  M_ADD_WINDOW
  M_CONFIGURE_WINDOW
  M_EXTENDED_MSG
  MX_VISIBLE_ICON_NAME
  MX_ENTER_WINDOW
  MX_LEAVE_WINDOW
  MX_PROPERTY_CHANGE
  MX_PROPERTY_CHANGE_NONE
  MX_PROPERTY_CHANGE_BACKGROUND
  MX_PROPERTY_CHANGE_SWALLOW
  MAX_MSG_MASK
  MAX_XMSG_MASK
  HEADER_SIZE
  START_FLAG
  RESPONSE_READY
  RESPONSE_UNLOCK
  ON_EXIT
  INTSIZE</pre></blockquote>
<P>

<HR>
<A NAME="index">&nbsp;</A><H2>Index</H2>
<DL>
<DT><A HREF="#lbAB">NAME</A><DD>
<DT><A HREF="#lbAC">DESCRIPTION</A><DD>
<DT><A HREF="#lbAD">USAGE</A><DD>
<DT><A HREF="#lbAE">SEE ALSO</A><DD>
<DT><A HREF="#lbAF">EXPORTED CONSTANTS</A><DD>
</DL>
<HR>
This document was created by
man2html,
using the manual pages.<BR>
Time: 02:17:01 GMT, June 10, 2003


<?php decoration_window_end(); ?>

<!-- Automatically generated by perllib2php on 10-Jun-2003 -->
