<?php
//--------------------------------------------------------------------
//-  File          : documentation/manpages/template.php
//-  Project       : FVWM Home Page
//-  Programmer    : Uwe Pross
//--------------------------------------------------------------------

// This is an autogenerated file, use perllib2php to create it.

//--------------------------------------------------------------------
// this manpages should not appear in the navigation structure
// so we hide its contents from navgen
//--------------------------------------------------------------------
if(isset($navigation_check)) return;

$rel_path = "./../..";

//--------------------------------------------------------------------
// load some global definitions
//--------------------------------------------------------------------
include_once("$rel_path/definitions.inc");

//--------------------------------------------------------------------
// Site definitions
//--------------------------------------------------------------------
$title          = "FVWM - Perl library - FVWM::Tracker::WindowList";
$heading        = "FVWM - Perl library - FVWM::Tracker::WindowList";
$link_name      = "Perl library";
$link_picture   = "pictures/icons/doc_manpages";
$parent_site    = "documentation";
$child_sites    = array();
$requested_file = basename(my_get_global("PHP_SELF", "SERVER"));
$this_site      = "manpages";

//--------------------------------------------------------------------
// load the layout file
//--------------------------------------------------------------------
if(!isset($site_has_been_loaded)) {
	$site_has_been_loaded = "true";
	if(isset($layout)) {
		$file = "$rel_path/layout_$layout.inc";
		if (file_exists($file)) $layout_file = $file;
	}
	include_once(sec_filename($layout_file));
	exit();
}
?>

<?php decoration_window_start("Manual page for FVWM::Tracker::WindowList in unstable branch (2.5.14)"); ?>

<H1>FVWM::Tracker::WindowList</H1>
Section: FVWM Perl library (3)<BR>Updated: 2005-08-24<BR>Source: <a href="ftp://ftp.fvwm.org/pub/fvwm/devel/sources/perllib/FVWM/Tracker/WindowList.pm">FVWM/Tracker/WindowList.pm</a><br>
<A HREF="#index">This page contents</A>
 - <a href="./">Return to main index</A><HR>

<A NAME="lbAB">&nbsp;</A>
<H2>DESCRIPTION</H2>

<A NAME="ixAAC"></A>
This is a subclass of <B><a href="<?php echo conv_link_target('./FVWM::Tracker.php');?>">FVWM::Tracker</a></B> that enables to read the window
information.
<P>

This tracker defines the following observables:
<P>

<blockquote><pre>    &quot;window added&quot;,
    &quot;window deleted&quot;,
    &quot;window properties updated&quot;,
    &quot;window moved&quot;,
    &quot;window resized&quot;,
    &quot;window iconified&quot;,
    &quot;window deiconified&quot;,
    &quot;window name updated&quot;,
    &quot;window stack updated&quot;,
    &quot;window icon updated&quot;,</pre></blockquote>
<A NAME="lbAC">&nbsp;</A>
<H2>SYNOPSYS</H2>

<A NAME="ixAAD"></A>
Using <B><a href="<?php echo conv_link_target('./FVWM::Module.php');?>">FVWM::Module</a></B> <TT>$module</TT> object:
<P>

<blockquote><pre>    my $tracker = $module-&gt;track(&quot;WindowList&quot;);
    my @windows = $tracker-&gt;windows;
    foreach my $window ($tracker-&gt;windows) {
        print &quot;+$window-&gt;{x}+$window-&gt;{y}, $window-&gt;{name}\n&quot;;
    }</pre></blockquote>
<P>

or:
<P>

<blockquote><pre>    my $tracker = $module-&gt;track(&quot;WindowList&quot;, &quot;winfo&quot;);
    my $x = $tracker-&gt;data(&quot;0x230002a&quot;)-&gt;{x};</pre></blockquote>
<P>

or:
<P>

<blockquote><pre>    my $tracker = $module-&gt;track(&quot;WindowList&quot;, $options);
    my $data = $tracker-&gt;data;
    while (my ($winId, $window) = each %$data) {
        next unless $window-&gt;match(&quot;CurrentPage, Iconified&quot;);
        $module-&gt;send(&quot;Iconify off&quot;, $winId);
    }</pre></blockquote>
<P>

Default <TT>$options</TT> string is: ``!stack !icons names winfo''
<A NAME="lbAD">&nbsp;</A>
<H2>OVERRIDDEN METHODS</H2>

<A NAME="ixAAE"></A>
<DL COMPACT>
<DT><B>new</B> <I>module</I> <I>params</I><DD>
<A NAME="ixAAF"></A>
It is possible the kind of window list.


<P>


To be written.
<DT><B>data</B> [<I>window-id</I>]<DD>
<A NAME="ixAAG"></A>
Returns array ref of window hash refs. or one window hash ref if
<I>window-id</I> is given.
<DT><B>dump</B> [<I>window-id</I>]<DD>
<A NAME="ixAAH"></A>
Works similarly to <B>data</B>, but returns debug lines for one or all windows.
</DL>
<A NAME="lbAE">&nbsp;</A>
<H2>METHODS</H2>

<A NAME="ixAAI"></A>
<DL COMPACT>
<DT><B>pageInfo</B> [<I>field</I>]<DD>
<A NAME="ixAAJ"></A>
Returns hash ref of page/desk info, or actual hash value using <B>field</B> as a key (if specified).
</DL>
<A NAME="lbAF">&nbsp;</A>
<H2>AUTHORS</H2>

<A NAME="ixAAK"></A>
<DL COMPACT>
<DT>Mikhael Goikhman &lt;<A HREF="mailto:migo@homemail.com">migo@homemail.com</A>&gt;<DD>
<A NAME="ixAAL"></A>

<DT>Scott Smedley<DD>
<A NAME="ixAAM"></A>

</DL>
<A NAME="lbAG">&nbsp;</A>
<H2>SEE ALSO</H2>

<A NAME="ixAAN"></A>
For more information, see <a href="<?php echo conv_link_target('./FVWM::Module.php');?>">FVWM::Module</a> and <a href="<?php echo conv_link_target('./FVWM::Tracker.php');?>">FVWM::Tracker</a>.
<P>

<HR>
<A NAME="index">&nbsp;</A><H2>Index</H2>
<DL>
<DT><A HREF="#lbAB">DESCRIPTION</A><DD>
<DT><A HREF="#lbAC">SYNOPSYS</A><DD>
<DT><A HREF="#lbAD">OVERRIDDEN METHODS</A><DD>
<DT><A HREF="#lbAE">METHODS</A><DD>
<DT><A HREF="#lbAF">AUTHORS</A><DD>
<DT><A HREF="#lbAG">SEE ALSO</A><DD>
</DL>
<HR>
This document was created by
man2html,
using the manual pages.<BR>
Time: 00:51:35 GMT, August 27, 2005


<?php decoration_window_end(); ?>

<!-- Automatically generated by perllib2php on 27-Aug-2005 -->
