<?php
//--------------------------------------------------------------------
//-  File          : documentation/manpages/template.php
//-  Project       : FVWM Home Page
//-  Programmer    : Uwe Pross
//--------------------------------------------------------------------

// This is an autogenerated file, use perllib2php to create it.

//--------------------------------------------------------------------
// this manpages should not appear in the navigation structure
// so we hide its contents from navgen
//--------------------------------------------------------------------
if (strlen("$navigation_check") > 0) return;

$rel_path = "./../..";

//--------------------------------------------------------------------
// load some global definitions
//--------------------------------------------------------------------
include("$rel_path/definitions.inc");

//--------------------------------------------------------------------
// Site definitions
//--------------------------------------------------------------------
$title          = "FVWM - Perl library - FVWM::Module::Toolkit";
$heading        = "FVWM - Perl library - FVWM::Module::Toolkit";
$link_name      = "Perl library";
$link_picture   = "pictures/icons/doc_manpages";
$parent_site    = "documentation";
$child_sites    = array();
$requested_file = basename(my_get_global("PHP_SELF", "SERVER"));
$this_site      = "manpages";

//--------------------------------------------------------------------
// load the layout file
//--------------------------------------------------------------------
if (strlen($site_has_been_loaded) == 0) {
	$site_has_been_loaded = "true";
	if (strlen($layout) > 0) {
		$file = "$rel_path/layout_$layout.inc";
		if (file_exists($file)) $layout_file = $file;
	}
	include(sec_filename($layout_file));
	exit();
}
?>

<?php decoration_window_start("Manual page for FVWM::Module::Toolkit in unstable branch (2.5.7)"); ?>

<H1>FVWM::Module::Toolkit</H1>
Section: FVWM Perl library (3)<BR>Updated: 2003-04-15<BR>Source: <a href="ftp://ftp.fvwm.org/pub/fvwm/devel/sources/perllib/FVWM/Module/Toolkit.pm">FVWM/Module/Toolkit.pm</a><br>
<A HREF="#index">This page contents</A>
 - <a href="./">Return to main index</A><HR>

<A NAME="lbAB">&nbsp;</A>
<H2>NAME</H2>

FVWM::Module::Toolkit - FVWM::Module with abstract widget toolkit attached
<A NAME="lbAC">&nbsp;</A>
<H2>SYNOPSIS</H2>

<A NAME="ixAAC"></A>
Only to be uses to implement concrete toolkit subclasses.
<P>

<blockquote><pre>    package FVWM::Module::SomeToolkit;
    # this automatically sets the base class and tries &quot;use SomeToolkit;&quot;
    use FVWM::Module::Toolkit qw(base SomeToolkit);</pre></blockquote>
<P>

<blockquote><pre>    sub showError ($$;$) {
        my ($self, $error, $title) = @_;
        $title ||= $self-&gt;name . &quot; Error&quot;;</pre></blockquote>
<P>

<blockquote><pre>        # create a dialog box using SomeToolkit widgets
        SomeToolkit-&gt;Dialog(
            -title =&gt; $title,
            -text =&gt; $error,
            -buttons =&gt; ['Close'],
        );
    }</pre></blockquote>
<P>

<blockquote><pre>    sub eventLoop ($$) {
        my ($self, $event) = @_;</pre></blockquote>
<P>

<blockquote><pre>        # enter the SomeToolkit event loop with hooking $self-&gt;{istream}
        fileevent($self-&gt;{istream},
            read =&gt; sub {
                unless ($self-&gt;processPacket($self-&gt;readPacket)) {
                    $self-&gt;disconnect;
                    $top-&gt;destroy;
                }
            }
        );
        SomeToolkit-&gt;MainLoop;
    }</pre></blockquote>
<A NAME="lbAD">&nbsp;</A>
<H2>DESCRIPTION</H2>

<A NAME="ixAAD"></A>
The <B><u>FVWM::Module::Toolkit</u></B> package is a sub-class of <B><a href="<?php echo conv_link_target('./FVWM::Module.php');?>">FVWM::Module</a></B> that
is intended to be uses as the base of sub-classes that attach widget
toolkit library, like Perl/Tk or Gtk-Perl. It does some common work to load
widget toolkit libraries and to show an error in the external window like
xmessage if the needed libraries are not available.
<P>

This class overloads one method <B>addDefaultErrorHandler</B> and expects
sub-classes to overload the methods <B>showError</B> and <B>showMessage</B> to use
native widgets (these 2 methods in this class by themselves overwrite the
superclass versions by adding a title parameter).
<P>

This manual page details only those differences. For details on the
<FONT>API</FONT> itself, see FVWM::Module.
<A NAME="lbAE">&nbsp;</A>
<H2>METHODS</H2>

<A NAME="ixAAE"></A>
Only those methods that are not available in <B><a href="<?php echo conv_link_target('./FVWM::Module.php');?>">FVWM::Module</a></B>, or are overloaded
are covered here:
<DL COMPACT>
<DT><B>showError</B> <I>msg</I> [<I>title</I>]<DD>
<A NAME="ixAAF"></A>
This method is intended to be overridden in subclasses to create a dialog box
using the corresponding widgets. The default fall back implementation is
to print an error message (with a title that is the module name by default)
to <FONT>STDERR</FONT>.


<P>


May be good for module diagnostics or any other purpose.
<DT><B>showMessage</B> <I>msg</I> [<I>title</I>]<DD>
<A NAME="ixAAG"></A>
This method is intended to be overridden in subclasses to create a dialog box
using the corresponding widgets. The default fall back implementation is
to print a message (with a title that is the module name by default)
to <FONT>STDERR</FONT>.


<P>


May be good for module debugging or any other purpose.
<DT><B>addDefaultErrorHandler</B><DD>
<A NAME="ixAAH"></A>
This methods adds a M_ERROR handler to automatically notify you that an error
has been reported by <FONT>FVWM</FONT>. The M_ERROR handler then calls <TT>&quot;showError()&quot;</TT>
with the received error text as a parameter to show it in a window.
</DL>
<A NAME="lbAF">&nbsp;</A>
<H2>AUTHOR</H2>

<A NAME="ixAAI"></A>
Mikhael Goikhman &lt;<A HREF="mailto:migo@homemail.com">migo@homemail.com</A>&gt;.
<A NAME="lbAG">&nbsp;</A>
<H2>SEE ALSO</H2>

<A NAME="ixAAJ"></A>
For more information, see fvwm, <a href="<?php echo conv_link_target('./FVWM::Module.php');?>">FVWM::Module</a>, <a href="<?php echo conv_link_target('./FVWM::Module::Gtk.php');?>">FVWM::Module::Gtk</a>,
FVWM::Module::Gtk2, <a href="<?php echo conv_link_target('./FVWM::Module::Tk.php');?>">FVWM::Module::Tk</a>.
<P>

<HR>
<A NAME="index">&nbsp;</A><H2>Index</H2>
<DL>
<DT><A HREF="#lbAB">NAME</A><DD>
<DT><A HREF="#lbAC">SYNOPSIS</A><DD>
<DT><A HREF="#lbAD">DESCRIPTION</A><DD>
<DT><A HREF="#lbAE">METHODS</A><DD>
<DT><A HREF="#lbAF">AUTHOR</A><DD>
<DT><A HREF="#lbAG">SEE ALSO</A><DD>
</DL>
<HR>
This document was created by
man2html,
using the manual pages.<BR>
Time: 00:52:00 GMT, April 19, 2003


<?php decoration_window_end(); ?>

<!-- Automatically generated by perllib2php on 19-Apr-2003 03:51:35 -->
