<?php
//--------------------------------------------------------------------
//-  File          : documentation/manpages/template.php
//-  Project       : FVWM Home Page
//-  Programmer    : Uwe Pross
//--------------------------------------------------------------------

// This is an autogenerated file, use perllib2php to create it.

//--------------------------------------------------------------------
// this manpages should not appear in the navigation structure
// so we hide its contents from navgen
//--------------------------------------------------------------------
if(isset($navigation_check)) return;

$rel_path = "./../..";

//--------------------------------------------------------------------
// load some global definitions
//--------------------------------------------------------------------
include_once("$rel_path/definitions.inc");

//--------------------------------------------------------------------
// Site definitions
//--------------------------------------------------------------------
$title          = "FVWM - Perl library - index";
$heading        = "FVWM - Perl library - index";
$link_name      = "Perl library";
$link_picture   = "pictures/icons/doc_manpages";
$parent_site    = "documentation";
$child_sites    = array();
$requested_file = basename(my_get_global("PHP_SELF", "SERVER"));
$this_site      = "manpages";

//--------------------------------------------------------------------
// load the layout file
//--------------------------------------------------------------------
if(!isset($site_has_been_loaded)) {
	$site_has_been_loaded = "true";
	if(isset($layout)) {
		$file = "$rel_path/layout_$layout.inc";
		if (file_exists($file)) $layout_file = $file;
	}
	include_once(sec_filename($layout_file));
	exit();
}
?>

<?php decoration_window_start("Manual page for index in unstable branch (2.5.8)"); ?>

<H1>Perl Library Index</H1>
Section: FVWM Perl library (3)<BR>Updated: 2003-11-01<BR><A HREF="#index">This page contents</A>
 - <a href="./">Return to main index</A><HR>

<A NAME="lbAB">&nbsp;</A>
<H2>NAME</H2>

index - lists all available help topics
<A NAME="lbAC">&nbsp;</A>
<H2>DESCRIPTION</H2>

<A NAME="ixAAC"></A>
Recent <I><a href="<?php echo conv_link_target('./../manpages/unstable/fvwm.php');?>">fvwm</a></I> versions install the Perl library that makes creating
<FONT>FVWM</FONT> modules in Perl possible and easy.
<P>

You may read the Perl library documentation locally by running:
<P>

<blockquote><pre>    % fvwm-perllib man &lt;topic&gt;</pre></blockquote>
<P>

Available topics:
<P>

<blockquote><pre>    <u>index</u>
    <a href="<?php echo conv_link_target('./tutorial.php');?>">tutorial</a>
    <a href="<?php echo conv_link_target('./FVWM::Commands.php');?>">FVWM::Commands</a>
    <a href="<?php echo conv_link_target('./FVWM::Constants.php');?>">FVWM::Constants</a>
    <a href="<?php echo conv_link_target('./FVWM::Event.php');?>">FVWM::Event</a>
    <a href="<?php echo conv_link_target('./FVWM::EventNames.php');?>">FVWM::EventNames</a>
    <a href="<?php echo conv_link_target('./FVWM::Module.php');?>">FVWM::Module</a>
    <a href="<?php echo conv_link_target('./FVWM::Module::Gtk.php');?>">FVWM::Module::Gtk</a>
    <a href="<?php echo conv_link_target('./FVWM::Module::Gtk2.php');?>">FVWM::Module::Gtk2</a>
    <a href="<?php echo conv_link_target('./FVWM::Module::Tk.php');?>">FVWM::Module::Tk</a>
    <a href="<?php echo conv_link_target('./FVWM::Module::Toolkit.php');?>">FVWM::Module::Toolkit</a>
    <a href="<?php echo conv_link_target('./FVWM::Tracker.php');?>">FVWM::Tracker</a>
    <a href="<?php echo conv_link_target('./FVWM::Tracker::Colorsets.php');?>">FVWM::Tracker::Colorsets</a>
    <a href="<?php echo conv_link_target('./FVWM::Tracker::GlobalConfig.php');?>">FVWM::Tracker::GlobalConfig</a>
    <a href="<?php echo conv_link_target('./FVWM::Tracker::ModuleConfig.php');?>">FVWM::Tracker::ModuleConfig</a>
    <a href="<?php echo conv_link_target('./FVWM::Tracker::PageInfo.php');?>">FVWM::Tracker::PageInfo</a>
    <a href="<?php echo conv_link_target('./FVWM::Tracker::Scheduler.php');?>">FVWM::Tracker::Scheduler</a>
    <a href="<?php echo conv_link_target('./FVWM::Tracker::WindowList.php');?>">FVWM::Tracker::WindowList</a>
    <a href="<?php echo conv_link_target('./General::FileSystem.php');?>">General::FileSystem</a>
    <a href="<?php echo conv_link_target('./General::Parse.php');?>">General::Parse</a></pre></blockquote>
<P>

For example:
<P>

<blockquote><pre>    % fvwm-perllib man FVWM::Module</pre></blockquote>
<A NAME="lbAD">&nbsp;</A>
<H2>AUTHOR</H2>

<A NAME="ixAAD"></A>
Mikhael Goikhman &lt;<A HREF="mailto:migo@homemail.com">migo@homemail.com</A>&gt;.
<P>

<HR>
<A NAME="index">&nbsp;</A><H2>Index</H2>
<DL>
<DT><A HREF="#lbAB">NAME</A><DD>
<DT><A HREF="#lbAC">DESCRIPTION</A><DD>
<DT><A HREF="#lbAD">AUTHOR</A><DD>
</DL>
<HR>
This document was created by
man2html,
using the manual pages.<BR>
Time: 00:48:38 GMT, November 01, 2003


<?php decoration_window_end(); ?>

<!-- Automatically generated by perllib2php on 01-Nov-2003 -->
