<?php
//--------------------------------------------------------------------
//-  File          : documentation/manpages/template.php
//-  Project       : FVWM Home Page
//-  Programmer    : Uwe Pross
//--------------------------------------------------------------------

// This is an autogenerated file, use perllib2php to create it.

//--------------------------------------------------------------------
// this manpages should not appear in the navigation structure
// so we hide its contents from navgen
//--------------------------------------------------------------------
if(isset($navigation_check)) return;

$rel_path = "./../..";

//--------------------------------------------------------------------
// load some global definitions
//--------------------------------------------------------------------
include("$rel_path/definitions.inc");

//--------------------------------------------------------------------
// Site definitions
//--------------------------------------------------------------------
$title          = "FVWM - Perl library - tutorial";
$heading        = "FVWM - Perl library - tutorial";
$link_name      = "Perl library";
$link_picture   = "pictures/icons/doc_manpages";
$parent_site    = "documentation";
$child_sites    = array();
$requested_file = basename(my_get_global("PHP_SELF", "SERVER"));
$this_site      = "manpages";

//--------------------------------------------------------------------
// load the layout file
//--------------------------------------------------------------------
if(!isset($site_has_been_loaded)) {
	$site_has_been_loaded = "true";
	if(isset($layout)) {
		$file = "$rel_path/layout_$layout.inc";
		if (file_exists($file)) $layout_file = $file;
	}
	include(sec_filename($layout_file));
	exit();
}
?>

<?php decoration_window_start("Manual page for tutorial in unstable branch (2.5.8)"); ?>

<H1>Perl Library Tutorial</H1>
Section: FVWM Perl library (3)<BR>Updated: 2003-11-01<BR><A HREF="#index">This page contents</A>
 - <a href="./">Return to main index</A><HR>

<A NAME="lbAB">&nbsp;</A>
<H2>NAME</H2>

tutorial - common techniques for writting FVWM modules
<A NAME="lbAC">&nbsp;</A>
<H2>TUTORIAL</H2>

<A NAME="ixAAC"></A>
<A NAME="lbAD">&nbsp;</A>
<H2>What is a window manager</H2>

<A NAME="ixAAD"></A>
A window manager is a program that runs on top of the X Window
System and manages windows, menus, key and mouse bindings, virtual
desktops and pages, draws window decorations using defined colors or
images, title-bar buttons and fonts.  It may also manage such things
as root background, mouse cursors, sounds, run applications and
do other nice things.
<A NAME="lbAE">&nbsp;</A>
<H2>What is a module</H2>

<A NAME="ixAAE"></A>
In the unix traditions, different functionality may be implemented
by separate programs to reduce a bloat. A module is an optional
program that is intended to extend the window manager using a defined
module protocol.
<P>

<FONT>FVWM</FONT> modules are spawned by the main <I><a href="<?php echo conv_link_target('./../manpages/unstable/fvwm.php');?>">fvwm</a></I> executable. They
usually listen to the window manager events, do some useful work and
send back commands for execution. There are transient modules that
exit immediately or shortly, and persistent modules that exit
together with a window manager or when a user requests.  Some
modules may control windows or other modules. Some modules may supply
a <FONT>GUI</FONT>, others may be non interactive.
<A NAME="lbAF">&nbsp;</A>
<H2>Creating a simple module</H2>

<A NAME="ixAAF"></A>
Let's create a module that shows a flash window for one second when
you change pages. We will use <I>xmessage</I> with nifty options for our
flash purposes, but you may use your fantasy to do this better.
<P>

First, we should understand when our module works. Usually a module
does nothing (sleeps) and is awaken when something interesting
happens. This is achieved using events. A module defines events that
it is interesting to receive and set-ups event handlers (perl
functions) to be called when the event happens. Then a module enters
the event loop where it sleeps all the time until one or another
event happens. Most of the module work is done in the event
handlers. When an event is processed, the module enters the event
loop again.
<P>

In our case, we should listen to an <FONT>FVWM</FONT> event <I>M_NEW_PAGE</I>. The list
of all events may be found in FVWM::Constants. When we receive
the event we want to get new page coordinates and display them
using our special xmessage window.
<P>

Now, from theory to practice. The header of all modules written in
Perl is pretty standard:
<P>

<blockquote><pre>    #!/usr/bin/perl -w</pre></blockquote>
<P>

<blockquote><pre>    use lib `fvwm-perllib dir`;
    use FVWM::Module;</pre></blockquote>
<P>

Then create the actual module object:
<P>

<blockquote><pre>    my $module = new FVWM::Module(
        Mask =&gt; M_NEW_PAGE | M_NEW_DESK,
        Debug =&gt; 1,
    );</pre></blockquote>
<P>

The <B>Debug</B> option tells to print the event names that a module
receives to help writing a module, it also echoes all sent commands.
The <B>Mask</B> option tells which events a module wants to receive, in
our case these are events generated on the page and desk changes.
<P>

To handle events, event handlers that are perl functions, should be
defined. It is ok not to define any event handler for <I>M_NEW_DESK</I>
and to define two event handlers for <I>M_NEW_PAGE</I>. But for our
purposes one <I>M_NEW_PAGE</I> would be more than enough:
<P>

<blockquote><pre>    $module-&gt;addHandler(M_NEW_PAGE, \&amp;gotNewPage);</pre></blockquote>
<P>

It is a time to implement our <TT>&quot;gotNewPage&quot;</TT> function that will be
called every time the desktop page is changed.
<P>

<blockquote><pre>    sub gotNewPage {
        my ($module, $event) = @_;</pre></blockquote>
<P>

<blockquote><pre>        my $width  = $event-&gt;_vp_width;
        my $height = $event-&gt;_vp_height;</pre></blockquote>
<P>

<blockquote><pre>        if (!$width || !$height) {
            # this may happen when doing DeskTopSize 1x1 on page 2 2
            return;
        }
        my $page_nx = int($event-&gt;_vp_x / $width);
        my $page_ny = int($event-&gt;_vp_y / $height);</pre></blockquote>
<P>

<blockquote><pre>        # actually show the flash
        $module-&gt;send(&quot;Exec xmessage -name FlashWindow \
            -bg cyan -fg white -center -timeout 1 -button '' \
            -xrm '*cursorName: none' -xrm '*borderWidth: 2' \
            -xrm '*borderColor: yellow' -xrm '*Margin: 12' \
            '($page_nx, $page_ny)'&quot;);
    }</pre></blockquote>
<P>

All event handlers are called with 2 parameters, a module and an
event objects. The arguments of the event are described in
FVWM::EventNames. Each event type has its own arguments. Our
<I>M_NEW_PAGE</I> has 5 arguments: vp_x vp_y desk vp_width vp_height.
We should do some calculations to get the page numbers from viewport
coordinates.
<P>

The <B>send</B> method passes the command to <I><a href="<?php echo conv_link_target('./../manpages/unstable/fvwm.php');?>">fvwm</a></I> for execution.
It would be better to set-up the FlashWindow specially:
<P>

<blockquote><pre>    $module-&gt;send(&quot;Style FlashWindow StaysOnTop, NoTitle, NoHandles, \
        BorderWidth 10, WindowListSkip, NeverFocus, UsePPosition&quot;);</pre></blockquote>
<P>

Finally, all persistent modules should enter the event loop:
<P>

<blockquote><pre>    $module-&gt;eventLoop;</pre></blockquote>
<P>

The full module source that we just wrote is available at
<A HREF="ftp://ftp.fvwm.org/pub/fvwm/devel/sources/tests/perl/module-flash">ftp://ftp.fvwm.org/pub/fvwm/devel/sources/tests/perl/module-flash</A> .
To run it execute this fvwm command:
<P>

<blockquote><pre>    Module /path/to/module-flash</pre></blockquote>
<P>

To kill the module, execute:
<P>

<blockquote><pre>    KillModule /path/to/module-flash</pre></blockquote>
<A NAME="lbAG">&nbsp;</A>
<H2>Creating a more functional module</H2>

<A NAME="ixAAG"></A>
Let's extend our new-page-flash example above and add a way to stop
our module and to define another string format. This would be
possible using the following <I><a href="<?php echo conv_link_target('./../manpages/unstable/fvwm.php');?>">fvwm</a></I> commands:
<P>

<blockquote><pre>    SendToModule /path/to/module-flash stop
    SendToModule /path/to/module-flash format '[%d %d]'</pre></blockquote>
<P>

To handle such commands, we should define <I>M_STRING</I> event handler.
<P>

<blockquote><pre>    use General::Parse;
    my $format = &quot;(%d, %d)&quot;;  # the default format</pre></blockquote>
<P>

<blockquote><pre>    $module-&gt;mask($module-&gt;mask | M_STRING);
    $module-&gt;addHandler(M_STRING, sub {
        my ($module, $event) = @_;
        my $line = $event-&gt;_text;
        my ($action, @args) = getTokens($line);</pre></blockquote>
<P>

<blockquote><pre>        if ($action eq &quot;stop&quot;) {
            $module-&gt;terminate;
        } elsif ($action eq &quot;format&quot;) {
            $format = $args[0];
        }
    });</pre></blockquote>
<P>

Now, let convert our module to be <FONT>GTK+</FONT> based and not to be
dependent on <I>xmessage</I>.
<P>

<blockquote><pre>    use lib `fvwm-perllib dir`;
    use FVWM::Module::Gtk;
    use Gtk;
    init Gtk;</pre></blockquote>
<P>

<blockquote><pre>    my $format = &quot;(%d, %d)&quot;;
    my $module = new FVWM::Module::Gtk(Mask =&gt; M_NEW_PAGE);</pre></blockquote>
<P>

<blockquote><pre>    $module-&gt;addHandler(M_NEW_PAGE, sub {
        my ($module, $event) = @_;</pre></blockquote>
<P>

<blockquote><pre>        my $width  = $event-&gt;_vp_width;
        my $height = $event-&gt;_vp_height;</pre></blockquote>
<P>

<blockquote><pre>        if (!$width || !$height) {
            return;
        }
        my $page_nx = int($event-&gt;_vp_x / $width);
        my $page_ny = int($event-&gt;_vp_y / $height);</pre></blockquote>
<P>

<blockquote><pre>        # actually show the flash
        my ($w, $h) = (80, 50);
        my $string = sprintf($format, $page_nx, $page_ny);</pre></blockquote>
<P>

<blockquote><pre>        my $window = new Gtk::Window('toplevel');
        $window-&gt;set_title(&quot;FlashWindow&quot;);
        $window-&gt;set_border_width(5);
        $window-&gt;set_usize($w, $h);
        $window-&gt;set_uposition(($width - $w) / 2, ($height - $h) / 2);</pre></blockquote>
<P>

<blockquote><pre>        my $frame = new Gtk::Frame();
        $window-&gt;add($frame);
        $frame-&gt;set_shadow_type('etched_out');</pre></blockquote>
<P>

<blockquote><pre>        my $label = new Gtk::Label($string);
        $frame-&gt;add($label);
        $window-&gt;show_all;</pre></blockquote>
<P>

<blockquote><pre>        $SIG{ALRM} = sub { $window-&gt;destroy(); };
        alarm(1);
    });</pre></blockquote>
<P>

<blockquote><pre>    $module-&gt;eventLoop;</pre></blockquote>
<P>

The full module source that we just wrote is available at
<A HREF="ftp://ftp.fvwm.org/pub/fvwm/devel/sources/tests/perl/module-gtkflash">ftp://ftp.fvwm.org/pub/fvwm/devel/sources/tests/perl/module-gtkflash</A> .
<A NAME="lbAH">&nbsp;</A>
<H2>EXAMPLES</H2>

<A NAME="ixAAH"></A>
Currently see <I><A HREF="ftp://ftp.fvwm.org/pub/fvwm/devel/sources/tests/perl/">ftp://ftp.fvwm.org/pub/fvwm/devel/sources/tests/perl/</A></I>
for examples.
<P>

Learning the sources of <B><a href="<?php echo conv_link_target('./../manpages/unstable/FvwmPerl.php');?>">FvwmPerl</a></B>, <B><a href="<?php echo conv_link_target('./../manpages/unstable/FvwmDebug.php');?>">FvwmDebug</a></B>, <B><a href="<?php echo conv_link_target('./../manpages/unstable/FvwmGtkDebug.php');?>">FvwmGtkDebug</a></B>
modules may help too.
<A NAME="lbAI">&nbsp;</A>
<H2>SEE ALSO</H2>

<A NAME="ixAAI"></A>
See <a href="<?php echo conv_link_target('./FVWM::Module.php');?>">FVWM::Module</a> and <a href="<?php echo conv_link_target('./FVWM::Module::Gtk.php');?>">FVWM::Module::Gtk</a> for the module <FONT>API</FONT>.
<A NAME="lbAJ">&nbsp;</A>
<H2>AUTHOR</H2>

<A NAME="ixAAJ"></A>
Mikhael Goikhman &lt;<A HREF="mailto:migo@homemail.com">migo@homemail.com</A>&gt;.
<P>

<HR>
<A NAME="index">&nbsp;</A><H2>Index</H2>
<DL>
<DT><A HREF="#lbAB">NAME</A><DD>
<DT><A HREF="#lbAC">TUTORIAL</A><DD>
<DT><A HREF="#lbAD">What is a window manager</A><DD>
<DT><A HREF="#lbAE">What is a module</A><DD>
<DT><A HREF="#lbAF">Creating a simple module</A><DD>
<DT><A HREF="#lbAG">Creating a more functional module</A><DD>
<DT><A HREF="#lbAH">EXAMPLES</A><DD>
<DT><A HREF="#lbAI">SEE ALSO</A><DD>
<DT><A HREF="#lbAJ">AUTHOR</A><DD>
</DL>
<HR>
This document was created by
man2html,
using the manual pages.<BR>
Time: 00:48:40 GMT, November 01, 2003


<?php decoration_window_end(); ?>

<!-- Automatically generated by perllib2php on 01-Nov-2003 -->
