Submitted by Christine (pebcak/saigo)
Christine says:<br />
I started glassy when all those fancy transparency were the thing too
have. The fvwm got some unofficial patches, so it has
hover-windowbuttons, rounded corners and a buttonwidth that's different
from the decorations height.

You can find the wallpaper <a
href="http://another-modus.deviantart.com/art/simply-captured-4703246">here</a>

the font is hooge<br/>
the script for the weatherdisplay was made by stonecrest
