A setup uses the Super_L for most FVWM-related operations.  FvwmButtons in
the bottom left corner and the icons appear/disappear when Super_L is
pressed/released.  Also, FvwmButtons is shown for a second or so when
the mouse pointer hits a screen edge.  Switching pages with EdgeScroll
still works.  All these tricks are possible with the new Schedule
command.  Finally, a window thumbnail used as its icon is produced
when the window has had focus for some time, not when it is being
iconified.  This makes FVWM feel more responsive.  <a
href="http://www.cl.cam.ac.uk/~pz215/editing/windows.html">More
...</a>
