Submitted by Axelle Apvrille<br />
<br />
Basically, my configuration is taken from <a href="http://pemarchandet.free.fr/">here</a> that
I customized to my likes. Transparent window titles for inactive windows.
Small vertical pager. Possibility to roll a window to its window title (on
the left in my case). Transparent menus (doesn't show on the
screenshot). There are also two applications which are transparent and
sticky so that they look like they are on the root window (your idea!).
Those applications are on the bottom left (a slide show with 2 xbiffs)
and the other one on the right, with the time, various widgets and
action buttons. This app is named a Crocbar, and written in Java. (but
lightweight, yes, yes). But that's not part of FVWM. Yet, it's a
neat way to have something that looks like a FvwmButtons module or
dock.<br /><br />
My configuration is hosted <a href="http://wikisec.free.fr/unix/axl-fvwm.tar.gz">here</a>
