	  Submitted by Ives Aerts.
	  The screenshot
	  shows xmms, gfontsel, rxvt with vim and my FvwmButtons. The three
	  half-height buttons with the up arrows open up wharf-like button
	  arrays when pressed.
	  Menus and title bars are lightly gradiented and the (vector) titlebar
	  buttons were stolen from an old post to the fvwm mailing list. What
	  you can't see are all kinds of nifty keyboard shortcuts to popup/hide
	  mutt (mail reader), switch between windows and desks, etc.
