
<table width="100%" border="0" cellpadding="0" cellspacing="0" summary="" class="decorated">
<?php $theme_object->decoration_top_line(); ?>
<tr>
<?php $theme_object->decoration_left_cell(); ?>
<td bgcolor="<?php echo $theme_object->style_array['window_bg']; ?>">
<table cellpadding="5" summary="" width="100%">
<tr>
<td valign="top" 
    align="center" 
    bgcolor="<?php echo $theme_object->style_array['window_bg']; ?>" 
    class="windowcontents">
You can change the background color to see transparent logos on different backgrounds.<br>
<a href="?window_bg=%23ffffff&window_fg=%23000000" style="color:<?php echo $theme_object->style_array['window_fg'];?>">white</a>&nbsp;
<a href="?window_bg=%23cccccc&window_fg=%23000000" style="color:<?php echo $theme_object->style_array['window_fg'];?>">grey80</a>&nbsp;
<a href="?window_bg=%237f7f7f&window_fg=%23000000" style="color:<?php echo $theme_object->style_array['window_fg'];?>">grey50</a>&nbsp;
<a href="?window_bg=%234d4d4d&window_fg=%23ffffff" style="color:<?php echo $theme_object->style_array['window_fg'];?>">grey30</a>&nbsp;
<a href="?window_bg=%23000000&window_fg=%23ffffff" style="color:<?php echo $theme_object->style_array['window_fg'];?>">black</a>&nbsp;
<a href="?window_bg=%23ff0000&window_fg=%23000000" style="color:<?php echo $theme_object->style_array['window_fg'];?>">red</a>&nbsp;
<a href="?window_bg=%2300ff00&window_fg=%23000000" style="color:<?php echo $theme_object->style_array['window_fg'];?>">green</a>&nbsp;
<a href="?window_bg=%230000ff&window_fg=%23000000" style="color:<?php echo $theme_object->style_array['window_fg'];?>">blue</a>&nbsp;
<a href="?window_bg=%23ffff00&window_fg=%23000000" style="color:<?php echo $theme_object->style_array['window_fg'];?>">yellow</a>&nbsp;
<a href="?window_bg=%23ff00ff&window_fg=%23000000" style="color:<?php echo $theme_object->style_array['window_fg'];?>">purple</a>&nbsp;
<a href="?window_bg=%2300ffff&window_fg=%23000000" style="color:<?php echo $theme_object->style_array['window_fg'];?>">magenta</a>&nbsp;
<a href="." style="color:<?php echo $theme_object->style_array['window_fg'];?>">default</a>&nbsp;
</td>
</tr>
</table>
</td>
<?php $theme_object->decoration_right_cell(); ?>
</tr>
<?php $theme_object->decoration_bottom_line(); ?>
</table>
<br>