<?php 

$logo_array[2] = array("1000Sun/fvwm2_FIN_emblem_1.png",
                             "1000Sun/fvwm2_FIN_emblem_2.png",
                             "1000Sun/fvwm2_FIN_emblem_3.png",);

$logo_array[1] = array("1000Sun/fvwm2_FIN_3D_black.png",
                             "1000Sun/fvwm2_FIN_gimmed.png",
                             "1000Sun/fvwm2_FIN_gimmed_no_border.png",);

$logo_array[5] = array("1000Sun/fvwm2_FIN_flat.png",);

$logo_array[9] = array("Alex_Wallis/fvwm_logo_brick.png",);
$logo_array[10] = array("Alex_Wallis/fvwm_logo_fiery_shadow.png",);
$logo_array[11] = array("Alex_Wallis/fvwm_logo_fire.png",);
$logo_array[12] = array("Alex_Wallis/fvwm_logo_rainbow.png",);
$logo_array[13] = array("Alex_Wallis/fvwm_logo_shadow.png",);
$logo_array[14] = array("Alex_Wallis/fvwm_logo_transparent.png",);
// $logo_array[15] = array("Alex_Wallis/overview.png",);

$logo_array[16] = array("Anand_Tanna/logofvwm.png",);
// $logo_array[17] = array("Anand_Tanna/overview.png",);

// $logo_array[18] = array("Anna_MacLachlan/clearly-fvwm-small.png",);
// $logo_array[19] = array("Anna_MacLachlan/clearly-fvwm.png",);

$logo_array[20] = array("Anna_MacLachlan/clearly1.png",);

// $logo_array[21] = array("Anna_MacLachlan/jungle-overview.png",);
// $logo_array[22] = array("Anna_MacLachlan/jungle-set.png",);

$logo_array[23] = array("Anna_MacLachlan/jungle1.png",);
$logo_array[24] = array("Anna_MacLachlan/jungle2.png",);

$logo_array[25] = array("Annemarie_Rowson/fvwm.jpg",);
// $logo_array[26] = array("Annemarie_Rowson/overview.png",);

$logo_array[27] = array("Anthony_Lee/fvwmlogo.gif", "Anthony_Lee/fvwmlogo1.gif",);

$logo_array[29] = array("Anthony_Lee/logocatgreen.jpg",);
// $logo_array[30] = array("Anthony_Lee/overview.png",);

$logo_array[31] = array("Anthony_Lee/paw.png",);

// $logo_array[32] = array("Aric_Campling/felineinside.png",);
$logo_array[33] = array("Aric_Campling/linecat1.png",);
$logo_array[34] = array("Aric_Campling/logo-gradient_bg.png","Aric_Campling/logo-transparent_bg.png",);

// $logo_array[36] = array("Aric_Campling/logos-overview.png",);
$logo_array[37] = array("Branko_Collin/branko-1-fvwm.png",);
$logo_array[38] = array("Branko_Collin/branko-2-fvwm.png",);
// $logo_array[39] = array("Branko_Collin/overview.png",);

$logo_array[40] = array("Christopher_Culp/fvwm.gif",);
// $logo_array[41] = array("Christopher_Culp/fvwm.png",);

$logo_array[42] = array("Coji_Morishita/fvwm_banner.png",
                        "Coji_Morishita/fvwm_logo.png",
                        "Coji_Morishita/fvwm_logo_plus.png",
                        "Coji_Morishita/fvwm_sbanner_blue.png",
                        "Coji_Morishita/fvwm_sbanner_green.png",
                        "Coji_Morishita/fvwm_sbanner_red.png",
                        "Coji_Morishita/fvwm_sbanner_yellow.png",
                        "Coji_Morishita/fvwm_sym_logo.png",);

$logo_array[50] = array("Colin_May/Colin1.png",);
$logo_array[51] = array("Colin_May/Colin2.png",);
$logo_array[52] = array("Colin_May/Colin3.png","Colin_May/Colin5.png",);
$logo_array[53] = array("Colin_May/Colin4.png",);
$logo_array[55] = array("Colin_May/Colin6.png","Colin_May/Colin7.png",);
$logo_array[57] = array("Colin_May/Colin8.png",);

$logo_array[58] = array("Daniel_Gadziemski/fvwm1-2.png","Daniel_Gadziemski/fvwm1.png",);

$logo_array[60] = array("Daniel_Gadziemski/fvwm2-1.png",
                        "Daniel_Gadziemski/fvwm2-2.png",
                        "Daniel_Gadziemski/fvwm2-3.png",
                        "Daniel_Gadziemski/fvwm2-4.png",
                        "Daniel_Gadziemski/fvwm2-5.png",
                        "Daniel_Gadziemski/fvwm2.png");

$logo_array[66] = array("Daniel_Gadziemski/fvwm3-1.png","Daniel_Gadziemski/fvwm3.png",);
$logo_array[68] = array("Daniel_Gadziemski/fvwm4.png",);
$logo_array[69] = array("Daniel_Gadziemski/fvwm5.png",);
$logo_array[70] = array("Daniel_Gadziemski/fvwm6.png",);
$logo_array[71] = array("Daniel_Gadziemski/fvwm7.png",);

$logo_array[73] = array("Daniel_J_Parks/fvwmLogoCatHoriz.png",);

$logo_array[74] = array("Daniel_J_Parks/fvwmLogoGlowingChromelike.png","Daniel_J_Parks/fvwmLogoGlowingChromelike300x180bw.png",);
// $logo_array[75] = array("Daniel_J_Parks/fvwmLogoGlowingChromelike200x120.png",);
// $logo_array[76] = array("Daniel_J_Parks/fvwmLogoGlowingChromelike24x64.png",);
// $logo_array[77] = array("Daniel_J_Parks/fvwmLogoGlowingChromelike300x180.png",);

$logo_array[79] = array("David_Drummond/yellow_flower_fvwm_logo.png",);
$logo_array[80] = array("Eric_Hafner/logo.png",);
$logo_array[81] = array("Ester_Wilson/fvwm_1.png",);
$logo_array[82] = array("Ester_Wilson/fvwm_2.png",);
$logo_array[83] = array("Ester_Wilson/fvwm_3.png",);
$logo_array[84] = array("Ester_Wilson/fvwm_4.png",);
$logo_array[85] = array("Ester_Wilson/fvwm_5.png",);
$logo_array[86] = array("Ester_Wilson/fvwm_6.png",);

// $logo_array[87] = array("Ester_Wilson/overview.png",);

// $logo_array[88] = array("Felix_E_Klee/cloudy_sky.png",);
$logo_array[89] = array("Felix_E_Klee/cloudy_sky1.png","Felix_E_Klee/cloudy_sky2.png",);
$logo_array[91] = array("Felix_E_Klee/feline.png",);

// $logo_array[92] = array("Felix_E_Klee/fvwm_geometric_sans_serif.png",);

$logo_array[93] = array("Felix_E_Klee/fvwm_geometric_sans_serif1.png",
                        "Felix_E_Klee/fvwm_geometric_sans_serif2.png",
                        "Felix_E_Klee/fvwm_geometric_serif.png",);

// $logo_array[96] = array("Felix_E_Klee/logos-overview.png",);
// $logo_array[97] = array("Felix_E_Klee/logos.png",);
$logo_array[98] = array("Felix_E_Klee/overlapping_windows.png",);
$logo_array[99] = array("Felix_E_Klee/stacked_windows.png",);

$logo_array[100] = array("Felix_Wiemann/brightbg-1bit.png",
                         "Felix_Wiemann/brightbg-200.png",
                         "Felix_Wiemann/darkbg-1bit.png",
                         "Felix_Wiemann/darkbg-200.png",);
// $logo_array[102] = array("Felix_Wiemann/brightbg-300.png",);
// $logo_array[103] = array("Felix_Wiemann/brightbg-600.png",);
// $logo_array[106] = array("Felix_Wiemann/darkbg-300.png",);
// $logo_array[107] = array("Felix_Wiemann/darkbg-600.png",);
// $logo_array[108] = array("Felix_Wiemann/overview.png",);

$logo_array[109] = array("Gabriel_Feld/fvwm1.png",
                         "Gabriel_Feld/fvwm2.png",
                         "Gabriel_Feld/fvwm3.png",);
// $logo_array[112] = array("Gabriel_Feld/overview.png",);

$logo_array[113] = array("Geoffroy_Giraux/logo_fvwm_curved_bw.png",
                         "Geoffroy_Giraux/logo_fvwm_curved_noborder.png",);

// $logo_array[115] = array("Geoffroy_Giraux/overview.png",);

$logo_array[116] = array("Greg_Rymer/fvwm-transparent-black-template.png","Greg_Rymer/fvwm.png",);
// $logo_array[118] = array("Greg_Rymer/overview.png",);

$logo_array[119] = array("Ian_Remmler/3d.png",);
$logo_array[120] = array("Ian_Remmler/block.png",);
$logo_array[121] = array("Ian_Remmler/contrast.png",);
$logo_array[122] = array("Ian_Remmler/future.png",);
$logo_array[123] = array("Ian_Remmler/groovy-3d.png",);
// $logo_array[124] = array("Ian_Remmler/overview.png",);

$logo_array[125] = array("Julien_Guertault/Feline-Logo-Color.png",
                         "Julien_Guertault/Feline-Logo-Mono.png",);

$logo_array[127] = array("Keran/bullet.png",);
$logo_array[128] = array("Keran/carre.png",);
$logo_array[129] = array("Keran/danger.png",);
$logo_array[130] = array("Keran/exclamation.png",);
$logo_array[131] = array("Keran/feu.png",);
$logo_array[132] = array("Keran/forward.png",);
$logo_array[133] = array("Keran/horizon.png",);
$logo_array[134] = array("Keran/panneau.png",);
$logo_array[135] = array("Keran/pastille.png",);
$logo_array[136] = array("Keran/pastille2.png",);
$logo_array[137] = array("Keran/point.png",);
$logo_array[138] = array("Keran/sauvage.png",);
$logo_array[139] = array("Keran/sens_unique.png",);
$logo_array[140] = array("Keran/star.png",);
$logo_array[141] = array("Keran/troue.png",);

$logo_array[142] = array("Krzysztof_Bartczak/fvwm_logo1.png",
                         "Krzysztof_Bartczak/fvwm_logo2.png",
                         "Krzysztof_Bartczak/fvwm_logo3.png",);
// $logo_array[143] = array("Krzysztof_Bartczak/overview.png",);

$logo_array[144] = array("Ludovic_Recourchines/F5.png","Ludovic_Recourchines/F6.png",);

$logo_array[146] = array("Ludovic_Recourchines/LogoF.png",);

// $logo_array[147] = array("Ludovic_Recourchines/logos-overview.png",);

// $logo_array[148] = array("Michael_Gorniak/fvwm-logos-overview.png",);
// $logo_array[149] = array("Michael_Gorniak/fvwm-logos.png",);
$logo_array[150] = array("Michael_Gorniak/fvwm-logos1.png",
                         "Michael_Gorniak/fvwm-logos2.png",
                         "Michael_Gorniak/fvwm-logos3.png",);

$logo_array[153] = array("Michael_Gorniak/fvwm-logos4.png",);

$logo_array[154] = array("Michael_Gorniak/fvwm-logos5.png",
                         "Michael_Gorniak/fvwm-logos6.png",
                         "Michael_Gorniak/fvwm-logos7.png",);

$logo_array[157] = array("Olli_Kopakkala/fvwm_valmis.png",);

$logo_array[158] = array("Patrick_Collison/FVWM_medium.png",
                         "Patrick_Collison/FVWM_transparent.png",);

// $logo_array[160] = array("Patrick_Collison/overview.png",);

$logo_array[161] = array("Phil_Harper/SynthSkin_FVWM_Wallpaper-thumb.png",
                         "Phil_Harper/SynthSkin_Variation_Wallpaper-thumb.png",
                         "Phil_Harper/TigerSkin_FVWM_Black_Wallpaper-thumb.png",
                         "Phil_Harper/TigerSkin_FVWM_Wallpaper-thumb.png");

$logo_array[165] = array("Phil_Harper/black.png",
                         "Phil_Harper/fakefur.png",
                         "Phil_Harper/feeble.png",);

$logo_array[168] = array("Phil_Harper/fvwmbevel.png",);

$logo_array[169] = array("Phil_Harper/fvwmboxes3.png",
                         "Phil_Harper/fvwmboxes4bw.png",);

$logo_array[171] = array("Phil_Harper/fvwmporthole.png",);

// $logo_array[172] = array("Phil_Harper/fvwmpower2-overview.png",);
$logo_array[173] = array("Phil_Harper/fvwmpower2.png",);

$logo_array[174] = array("Phil_Harper/fvwmvert.png",);
// $logo_array[175] = array("Phil_Harper/overview.png",);
$logo_array[176] = array("Phil_Harper/plain.png",);
$logo_array[177] = array("Phil_Harper/tiger.png",
                         "Phil_Harper/tiger2.png",);

$logo_array[179] = array("Phil_Harper/tigerskin5.png",
                         "Phil_Harper/tigerskin6.png",);

$logo_array[181] = array("Russell_Martin/fvwm.png",);
// $logo_array[182] = array("Russell_Martin/overview.png",);

// $logo_array[183] = array("Scott_Smedley/fvwm-overview.png",);

$logo_array[184] = array("Scott_Smedley/fvwm01.png",
                         "Scott_Smedley/fvwm02.png",);

$logo_array[186] = array("Scott_Smedley/fvwm03.png",);
$logo_array[187] = array("Scott_Smedley/fvwm04.png",);

$logo_array[188] = array("Scott_Smedley/fvwm05.png",
                         "Scott_Smedley/fvwm06.png",);

$logo_array[190] = array("Scott_Smedley/fvwm07.png",);

$logo_array[191] = array("Slava_Finkelsteyn/fvwm1.jpg",
                         "Slava_Finkelsteyn/fvwm2.jpg",);

$logo_array[193] = array("Stefan_Bergmeier/logo-transparent.gif",
                         "Stefan_Bergmeier/logo-white.gif",);
// $logo_array[195] = array("Stefan_Bergmeier/logos-overview.png",);

$logo_array[196] = array("Stephen_Ford/fvwm.png",);

$logo_array[197] = array("Tadashi_Hikone/logo.png",);

// $logo_array[198] = array("Takashi_Toyooka/banner-3d.png",);
$logo_array[199] = array("Takashi_Toyooka/banner-sml-3d.png",
                         "Takashi_Toyooka/banner-sml-black.png",
                         "Takashi_Toyooka/banner-sml-white.png",
                         "Takashi_Toyooka/bannerbar-flat.png",
                         "Takashi_Toyooka/icon100-3d.png",
                         "Takashi_Toyooka/icon100-flat.png",);
// $logo_array[205] = array("Takashi_Toyooka/icon16-flat-black.png",);
// $logo_array[206] = array("Takashi_Toyooka/icon16-flat-white.png",);
// $logo_array[207] = array("Takashi_Toyooka/icon16-flat.png",);
// $logo_array[208] = array("Takashi_Toyooka/icon16-level-black.png",);
// $logo_array[209] = array("Takashi_Toyooka/icon16-level-white.png",);
// $logo_array[210] = array("Takashi_Toyooka/icon16-level.png",);
// $logo_array[211] = array("Takashi_Toyooka/icon32-3d.png",);
// $logo_array[212] = array("Takashi_Toyooka/icon32-flat.png",);

$logo_array[214] = array("Tian/logo_float.png",
                         "Tian/logo_float_bg.png",);

$logo_array[213] = array("Tian/logo_basic.png",
                         "Tian/logo_shaded.png",
                         "Tian/logo_sunny.png",);

$logo_array[218] = array("Tom_Krietemeyer/fvwm-logo.png",);
// $logo_array[219] = array("Tom_Krietemeyer/overview.png",);

// $logo_array[220] = array("Wolf_Bergenheim/overview.png",);
$logo_array[221] = array("Wolf_Bergenheim/tangram_FVWM_logo_banner.png",
                         "Wolf_Bergenheim/tangram_FVWM_logo_banner_rev.png",
                         "Wolf_Bergenheim/tangram_FVWM_logo_banner_white.png",
                         "Wolf_Bergenheim/tangram_FVWM_logo_menu.png",
                         "Wolf_Bergenheim/tangram_FVWM_logo_menu_rev.png",);

// $logo_array[226] = array("Wolf_Bergenheim/tangram_FVWM_logo_website.png",);
// $logo_array[227] = array("Wolf_Bergenheim/tangram_FVWM_logo_website_rev.png",);

?>
