	  Submitted by Maciej_Delmanowski.
Maciej says:

I used FVWM to create my own desktop enviroment. It's called
'FVWM - Crystal' and it's based on the unstable/CVS branch (2.5.6). It's features
include:

<ul>
<li>transparent panels/window titles</li>
<li>intensive use of mouse buttons; normal is using 2 buttons to make
  different tasks, usually all three are used</li>
<li>new look at user interface, for example close/minimize/kill functions
  are combined in one title-bar button; there are two modes of moving or
  maximizing a window; interface is clean and provides a lot of space on
  the desktop - all panels can be hid by just middle-clicking on the
  desktop</li>
<li>intensive use of keyboard shortcuts (example: numpad, used to control
  windows - resizing, moving, shading, etc. - has 37 different
  shortcuts); there are keys to control window placement, moving windows
  between dekstops and resizing them; also included is control over xmms
  with additional programs</li>
</ul>