	  Submitted by Ploum.
Ploum says:

I like a clean desktop. I created a gradient for my fvwm menu and I called
it  "ocean".  I used a blue  gradient  for the active  titlebar  and a grey
gradient for  inactive.  I  can  easily  switch between viewports  with
"alt+arrow". The icons are from <b>wm-icons</b>. You  can see in the top left
corner two tiny  fvwm buttons. The first is  to  hide/unhide zinf, the
audio player, the second is a "swallow" of  my jabber status. Clicking
on it hides/unhides the psi main window.

I put xplanet in the backround with tracking of some satellites. (you
can see ISS  and XMM). On   the right, this   is gkrellm and a  sticky
transprent aterm in the bottom. Only 3 lines, it's just to launch some
commands.

When I minimize an application, the icon is  sent to my vertical icon
box,  just under grkrellm,  but  I do it rarely.  I  prefer shading of
windows, like the xterm at the top of the screen.

I just discovered today the cool "Aqua" skin for GTK and the "Aqua" skin
for phoenix, my favourite browser.

I documented a lot my
<a href="fvwm2rc">fvwm2rc</a> file, but in french...

Yes, I hate taskbars and icons ! ;)
