	  Submitted by Len Philpot.
Len says:
it's simple (no transparent
terminals, multiple modules, etc., etc), but that might be a nice
contrast to all the "walk and talk" .fvwm2rc's out there. It does have
custom pixmaps buttons and titlebar, along with FvwmButtons on the
taskbar...
I'd like
to combine the maximize and restore buttons into one.
<p>
The question mark button brings up a form containing choices for all the
FVWM man pages, which launch in their own xterms.
