<?php
//--------------------------------------------------------
// This file has been generated automatically
// Please use the corresponding script to regenerate 
// this file
// GPL2 (c) Uwe Pross 2003
//--------------------------------------------------------
$db = array(
      0 => array(
                 'path' => './Julien_Coron',
                 'preview' => 'preview.gif',
                 'screenshot' => 'menu.png',
                 'date' => 1075643876,
                 'size' => 21963,
                 'dimension' => '233x394',
                 'description' => ' 	Sample menu submitted by Julien Coron.
 	The pixmaps are available
 	the <a href="http://julien.coron.free.fr/my_icons/">here</a>.
',
                 'rc' => array(
                               'name' => 'fvwmrc',
                               'size' => 4169,
                               'date' => 1075648286,
                               ),
                 ),
      1 => array(
                 'path' => './BlueMarble',
                 'preview' => 'preview.gif',
                 'screenshot' => 'menu.gif',
                 'date' => 1075643855,
                 'size' => 19207,
                 'dimension' => '239x237',
                 'description' => ' Sample menu submitted by Dan Espen using background pixmaps.
 Click here for	the <a href="@path@/background.xpm">background pixmap</a>.
',
                 'rc' => array(
                               'name' => 'fvwmrc',
                               'size' => 290,
                               'date' => 1075648299,
                               ),
                 ),
      2 => array(
                 'path' => './Tavis_Ormandy',
                 'preview' => 'preview.gif',
                 'screenshot' => 'menu_screenshot.png',
                 'date' => 1074550891,
                 'size' => 183687,
                 'dimension' => '488x419',
                 'description' => ' From Tavis Ormandy
',
                 'rc' => array(
                               'name' => 'fvwm2rc',
                               'size' => 15007,
                               'date' => 1074555431,
                               ),
                 ),
      );
?>
