	  Submitted by Andre Bonhote.
	  My desktop shows (of course) fvwm,
	  of which not much is being seen actually.
	  Only the root menu and the decorations are really fvwm-like.
	  I like gtk so I am using gnome's panels (top and bottom, left hand side).
	  There's an aterm window using transparency, gqmpeg and netscape, and, of
	  course, gkrellm running.
	  For the colors, I used grdb and grdb2fvwm, which takes gnome's colors
	  and fonts and puts it into my fvwm2rc. it's quite useful, I think.
