	  Submitted by Parv.
Parv says:
(fvwm 2.5.4) shows titles on bottom and on right hand side,
sticky windows with and without title-bars, FvwmPager, and
aterm with transparent background and tinting.
<p>
You can visit Parv's web site and see
the<A HREF="http://www103.pair.com/parv/comp/unix/cf/fvwm/#fvwm-2.5.4">
configuration file</a>.

See also the
<A HREF="http://www103.pair.com/parv/comp/graphic.comp/shot-fvwm-2.5.4-annotated.png">
annotated version of the screen shot</a>.
 	