Submitted by Jules Alberts.
Jules says:
The setup is like this: FVWM 2.5.7 on a Red Hat 9 box (PIII 500Mhz). I
like the interface to be as simple as possible without losing
functionality. GKrellm, a simple pager, a menu, application windows and
icons. That's it.<br>
Things I would
like to add is some eye-candy (transparancy) and finally get
FvwmTrackFocus.pl working :-) but on the whole I think this setup is nice
to work with.
