	  Submitted by Taviso.
Taviso says:

A Flat look, using vector buttons with solid color, loosely based on
a fluxbox look with wallpaper from QNX. The icons are from the wm-icons
package, and theres a transparent pager in the top left. Running fvwm-2.5.5 
on Linux Alpha and x86.

Taviso's submissions prompted some questions which he graciously answered:
<br>
Q: what is your file browser ?
<br>
A: its xftree, from the xfce project <a href="http://www.xfce.org/">http://www.xfce.org/</a>
<br>
Q: how do you change the look of this program ? (flat button bar style...)
<br>
A: its a gtk theme engine i use this one <a href="http://themes.freshmeat.net/projects/flat/">
http://themes.freshmeat.net/projects/flat/</a>
<br>
Q: how do you change the style of your browser ? (nice scroller !) 
<br>
A: thats the gtk theme engine again :) i just changed the prelighting to
blue to match my fvwm theme :)
