	  Submitted by Glen Lee Edwards.
This screenshot is intended to show the versatility of FvwmButtons.
FvwmButtons can swallow programs as well as menu items.  There are 3
separate FvwmButton panels active on this desktop.  MyBar1 is the
button on the right, and runs xbuffy, which monitors my incoming mail.
MyBar2, the bar across the bottom contains menu items and the
FvwmPager.  I have 24 active desktops.  The labeling, F1, F2,
etc. tells me which key combination to hit to go to that desktop.
MyBar3, which takes up the bulk of the screen, holds several programs
I constantly run and need quick access to.  All 3 bars are easily
iconized and removed from the screen with a simple key stroke designed
specifically for that individual bar, leaving me a clean and open
desktop to run additional programs.
<p>
Note: Check out Glen's excellent FVWM
<a href="http://www.holiness.ch/fvwm/">page</a>
for even more FVWM
screenshots and information.
