Submitted by Thomas Adam.<br>
This setup uses an old style - very similar to that of MWM and CDE.  The
window colors can be changed on-the-fly using a dynamic menu of defined
colorsets, although the inactive colorset is always 'skyblue3'.  The
buttonsbar at the bottom is FvwmButtons which has swallowed xbuffy, rxvt, a
"media panel" (to control mpc), xlassie, two instances of xloadtime, and
FvwmPager.  The whole this is panelised so that it is retractable.  I also
have a root menu which has acccess to some common programs I like to use. 
There are some keybindings to toggle features as well.<br>
Further information can be found at the
<a href="http://www.fvwmwiki.org/cgi/moin.cgi/FvwmMWM">fvwmwiki</a>.
