Submitted by Thomas Adam.<br>
Thomas says:<br>
This screenshot shows FVWM running with a modified fvwm-themes (mostly
stolen from 'default'). I have tried to emulate the look and feel of RH's
"AnotherLevel", by changing the window colour, and centering the title of
the windows.<br>

The icons and the panel that you can see are a customised version of
<a href="http://rox.sf.net">Rox-Filer</a> that complements FVWM extremely well.
