<p>Submitted by Andrey Startsev</p>

<p>Simple config for feline addict C coder and vim user like me, which I use and clone for about two years. It's dark themed highly modernized MWM looking with permanently removed annoying "close" button which I did always hit by mistake in my earlier window managers...</p>

<p>It implements three named desktops for me, true Quake terminal happily stolen from this forum somewhere, automatic maximizing, some special adjustments for informational message windows, Win-D "show desktop" (all current desktop windows minimizer), panic button, and it may require some further cleanup.</p>

<p>Windows policy is to keep windows locked on the single desktop, but free to "send" between them via window menu. This is I think most comfortable setup for me because I operate mostly from keyboard.</p>

<p>I used Pager for a while, but then, because I operate mostly from keyboard, I decided to turn it off. A matter of taste. And that's why I loved FVWM since first look: it enabled me to configure my desktop freely.</p>

<a href="2017-02-03_Andrey_Startsev-1290x1024/fvwmcfg.tar.gz">Fvwm Config + Icons</a>
