	  Second submission by Andre Bonhote.
          Normally, we show one screenshot per user, but just this once,
	  we'll show how desktops evolve over time.  This was submitted Dec 2002,
	  and the first one was submitted Oct 2000.
          <p>
	  Andre says:
	  This screenshot shows fvwm 2.5.5 (from cvs) with a lot of transparency.
	  Title bars, borders, menues and pagers (invisible at the moment) are all fully 
	  transparent, some are shaded to look blueish. Besides fvwm2, you see my logs 
	  in three aterms on the right side of the screen. Below that xchat and a small
	  gkrellm. On the left, there's mutt in an Eterm. The nice background is done
	  by xplanet and refreshed every 15 minutes.
