	  Submitted by Marc A. Lehmann.
This is an Xinerama desktop showing some interesting side mounted titles,
flat borders and gradients in the titlebars.
The @fvwm2rc@
is M4 based and contains some interesting stuff too.
<p>
Mark says:
... features XineramaSls, a really old fvwm config incrementally
updated to fvwm2 over the years. The config tries to implement the
following:
<ul>
<li>clean and reasonably fast (ok, gradients crept in over time ;)
<li>the active window must be very visible
<li>lots of virtual desktops, overlaps reduced to the minimum
<li>no unnecessary clutter, large terminals
<li>syslog on root-window using root-tail
</ul>
 	