	  Submitted by J C Lawrence.
The basic rules guiding this <a href="fvwm2rc">setup</a>:
<ul>
<li>
 Modal interfaces are evil.
<li>
 No icons will ever appear on any system I run.  
<li>
 Nothing ever gets dragged, nothing ever gets dropped.
<li>
 There will be no system controls which are bound to or only
 accessible via particular locations on the screen.
<li>
 Key bindings/keyboard acceleration is your friend.
<li>
 No Z-order limits on any controls or feature accessibility.
<li>
 All controls must be accessible and controllable without
 requiring prior access (such as by changing z-order or moving a
 window out of the way (BAD!)), or to any other particular window
 or X or WM widget or device.
</ul>
