#!/usr/bin/perl

use strict;

# List of full paths to manpages (currently must gziped .gz)
my $scrotlist = `ls */description.inc`;

# Index Page Header.
print q(---
layout : default
title : FVWM Desktop Screenshots
header-title : Screenshots
---
<h1>FVWM Screen Shots</h1>

);

my $description, my $basename, my $img, my $data;
while( $scrotlist =~ /(.+)$/mg) {
	$description = $1;
	($basename = $description) =~ s!/description.inc!!;
	print "\n\n";
	$img = `ls $basename/screenshot.*`;
	$img =~ s/\n//g;

	unless (-e "$basename/preview.png") {
		system("convert", "-scale", "160x120", $img, "$basename/preview.png");
	}

        print qq(<hr><div class="scrot">
	<a href="$img">
	<img src="${basename}/preview.png" alt="preview">
	</a></div>
	);

	$data = `cat $description`;
	print qq(<div class="scrot_desc">$data</div><br>);
}


