	  Submitted by J.G.A. van Riswick.
This is a screen shot of fvwm mimicking the cde environment.
The setup features motif-style window decorations and
shadow/hilight color calculations.  The colors are calculated in
a perl script, which also generates .xresources and .gtkrc files
so that a consistent color scheme is used throughout all
applications.  In addition, given background pixmaps are colored
in the same colors, who on turn are reflected in the colors of
the buttons on the pager.  To mimic the cde front panel (in the
bottom) I used the gnome panel with some custom applets added.
Left to be done to fully get the cde look are window decorations
for icons. 
You can dowload
CDEmu which includes config files and scripts
<a href="http://themes.freshmeat.net/projects/cdemu">
here</a>.
