<?php
//--------------------------------------------------------
// This file has been generated automatically
// Please use the corresponding script to regenerate 
// this file
// GPL2 (c) Uwe Pross 2003
//--------------------------------------------------------
$db = array(
      0 => array(
                 'path' => './brushedmetal',
                 'preview' => 'preview.gif',
                 'screenshot' => 'shot.png',
                 'date' => 1087847919,
                 'size' => 11886,
                 'dimension' => '474x292',
                 'description' => ' Brushed metal decoration taken from fvwm-theme.
',
                 'rc' => array(
                               'name' => 'brushedmetal_config.tgz',
                               'size' => 75900,
                               'date' => 1088344854,
                               ),
                 ),
      1 => array(
                 'path' => './simple',
                 'preview' => 'preview.png',
                 'screenshot' => 'shot2.png',
                 'date' => 1085333662,
                 'size' => 24475,
                 'dimension' => '321x389',
                 'description' => ' Simple but functional window decoration using MiniIcons and vector buttons. 
',
                 'rc' => array(
                               'name' => 'simple_decor_config.tgz',
                               'size' => 7969,
                               'date' => 1085334346,
                               ),
                 ),
      );
?>
