<?php
//--------------------------------------------------------
// This file has been generated automatically
// Please use the corresponding script to regenerate 
// this file
// GPL2 (c) Uwe Pross 2003
//--------------------------------------------------------
$db = array(
      0 => array(
                 'path' => './simple',
                 'preview' => 'preview.png',
                 'screenshot' => 'shot2.png',
                 'date' => 1085333662,
                 'size' => 24475,
                 'dimension' => '321x389',
                 'description' => ' Simple but functional window decoration using MiniIcons and vector buttons. 
',
                 'rc' => array(
                               'name' => 'simple_decor_config.tgz',
                               'size' => 7292,
                               'date' => 1085309607,
                               ),
                 ),
      );
?>
