<?php
//--------------------------------------------------------
// This file has been generated automatically
// Please use the corresponding script to regenerate 
// this file
// GPL2 (c) Uwe Pross 2003
//--------------------------------------------------------
$db = array(
      0 => array(
                 'path' => './winxp',
                 'preview' => 'preview.gif',
                 'screenshot' => 'shot.png',
                 'date' => 1106859395,
                 'size' => 9887,
                 'dimension' => '472x298',
                 'description' => ' Redmond XP decoration taken from fvwm-theme.
',
                 'rc' => array(
                               'name' => 'winxp_decor_config.tgz',
                               'size' => 21074,
                               'date' => 1106858656,
                               ),
                 ),
      1 => array(
                 'path' => './brushedmetal',
                 'preview' => 'preview.gif',
                 'screenshot' => 'shot.png',
                 'date' => 1087847919,
                 'size' => 11886,
                 'dimension' => '474x292',
                 'description' => ' Brushed metal decoration taken from fvwm-theme.
',
                 'rc' => array(
                               'name' => 'brushedmetal_config.tgz',
                               'size' => 76461,
                               'date' => 1106858650,
                               ),
                 ),
      2 => array(
                 'path' => './simple',
                 'preview' => 'preview.png',
                 'screenshot' => 'shot1.png',
                 'date' => 1085334076,
                 'size' => 4902,
                 'dimension' => '321x389',
                 'description' => ' Simple but functional window decoration using MiniIcons and vector buttons. 
',
                 'rc' => array(
                               'name' => 'simple_decor_config.tgz',
                               'size' => 8108,
                               'date' => 1106858642,
                               ),
                 ),
      );
?>
