<?php
//--------------------------------------------------------
// This file has been generated automatically
// Please use the corresponding script to regenerate 
// this file
// GPL2 (c) Uwe Pross 2003
//--------------------------------------------------------
$db = array(
      0 => array(
                 'path' => './An_Thi_Nguyen_Le-desk3-1152x864',
                 'preview' => 'preview.gif',
                 'screenshot' => 'screenshot.gif',
                 'date' => 1061361201,
                 'size' => 120776,
                 'dimension' => '1024x768',
                 'description' => ' A third  one by An Thi-Nguyen Le.   Here\'s also a screenshot
 	  of a   mockup of Gnutopia, a  rather  cheery BlackBox theme,
 	  with  the large   pager  retracted (another  thing I  fooled
 	  around  with.  Actually, all  the  buttons retract, just for
 	  the heck  of  it).    Cheery happy  yellowy  and   all that.
',
                 ),
      1 => array(
                 'path' => './An_Thi_Nguyen_Le-desk2-1152x864',
                 'preview' => 'preview.gif',
                 'screenshot' => 'screenshot.gif',
                 'date' => 1061360055,
                 'size' => 217183,
                 'dimension' => '1024x768',
                 'description' => ' By An  Thi-Nguyen   Le.  I got  really  really procrast-- I mean, bored, and
 fooled around with FvwmTheme for a while.  This particular scheme is
 borrowing heavily from the Enlightenment theme AbsoluteE (the blue version)
 and makes heavy use of the stretching pixmap feature of FvwmTheme.  The
 background is Tigert\'s Blue Space, the GKrellM theme is something obscure
 called 3051.
',
                 ),
      2 => array(
                 'path' => './An_Thi_Nguyen_Le-1152x864',
                 'preview' => 'preview.gif',
                 'screenshot' => 'screenshot.gif',
                 'date' => 1061326513,
                 'size' => 178879,
                 'dimension' => '1152x864',
                 'description' => ' 	  Submitted by An Thi-Nguyen Le.
 	  Simple  window  and    menu   decors  using diagonal     and
 	  backwards-diagonal gradients.    Buttons are actual defaults
 	  from fvwm.  :) The modules used are FvwmButtons (I\'d use the
 	  $fg and $bg variables for the swallowed shell but that makes
 	  it harder to read in this case), FvwmPager, FvwmIconMan (the
 	  very bestest icon manager around).  Dockapps are xpostit and
 	  wmnetselect.  On the right is GKrellM, nice themable stacked
 	  system monitors.
',
                 ),
      3 => array(
                 'path' => './Uwe_Pross-896x672',
                 'preview' => 'preview.gif',
                 'screenshot' => 'screenshot.png',
                 'date' => 1061240585,
                 'size' => 251660,
                 'dimension' => '896x672',
                 'description' => ' bla bla
',
                 ),
      );
?>
