<?php
//--------------------------------------------------------
// This file has been generated automatically
// Please use the corresponding script to regenerate 
// this file
// GPL2 (c) Uwe Pross 2003
//--------------------------------------------------------
$db = array(
      0 => array(
                 'path' => './An_Thi_Nguyen_Le-1152x864',
                 'preview' => 'preview.gif',
                 'screenshot' => 'screenshot.gif',
                 'date' => 1061319231,
                 'size' => 178879,
                 'description' => ' 	  Submitted by An Thi-Nguyen Le.
 	  Simple  window  and    menu   decors  using diagonal     and
 	  backwards-diagonal gradients.    Buttons are actual defaults
 	  from fvwm.  :) The modules used are FvwmButtons (I\'d use the
 	  $fg and $bg variables for the swallowed shell but that makes
 	  it harder to read in this case), FvwmPager, FvwmIconMan (the
 	  very bestest icon manager around).  Dockapps are xpostit and
 	  wmnetselect.  On the right is GKrellM, nice themable stacked
 	  system monitors.
',
                 ),
      1 => array(
                 'path' => './Uwe_Pross-896x672',
                 'preview' => 'preview.gif',
                 'screenshot' => 'screenshot.png',
                 'date' => 1058558290,
                 'size' => 251660,
                 'description' => ' bla bla
',
                 ),
      );
?>
